# 08.2007 Cvet

# Version info
{1}{}{     ArcReborn Developer Version 1.0a}

####################################################################################################################################
#
#       Months, Day of week
#
####################################################################################################################################

{21}{}{Январь}
{22}{}{Февраль}
{23}{}{Март}
{24}{}{Апрель}
{25}{}{Май}
{26}{}{Июнь}
{27}{}{Июль}
{28}{}{Август}
{29}{}{Сентябрь}
{30}{}{Октябрь}
{31}{}{Ноябрь}
{32}{}{Декабрь}

{33}{}{Воскресенье}
{34}{}{Понедельник}
{35}{}{Вторник}
{36}{}{Среда}
{37}{}{Четверг}
{38}{}{Пятница}
{39}{}{Суббота}

####################################################################################################################################
#
#       Material Types (from PROTO.MSG)
#
####################################################################################################################################

{40}{}{Стекло}
{41}{}{Металл}
{42}{}{Пластик}
{43}{}{Дерево}
{44}{}{Грязь}
{45}{}{Камень}
{46}{}{Цемент}
{47}{}{Кожа}

####################################################################################################################################
#
#       Misc
#
####################################################################################################################################

{50}{}{.}
{52}{}{,}
{53}{}{ }
{54}{}{ и }
{55}{}{ или }
###Пол

{56}{}{Мужчина}
{57}{}{Женщина}

#arcreborn характеристики полностью написанные
{58}{}{Здоровье}
{59}{}{Энергия}
{60}{}{Склонность к м./т.}
{61}{}{Грузоподъемность}
{62}{}{Дополнительный ущерб}
{63}{}{Очки действия}
{64}{}{Скорость выздоровления}
{65}{}{Модификатор Реакции}
{66}{}{Восстановление от яда}
{67}{}{Класс Брони}
{68}{}{Количество спутников}
{69}{}{Соп-е Ущербу}
{70}{}{Соп-е Магии}
{71}{}{Соп-е Огню}
{72}{}{Соп-е Яду}
{73}{}{Соп-е Эл-ву}
{74}{}{Критический удар}
{75}{}{Стоимость заклинаний}
####################################################################################################################################
#
#       Music/Video
#
####################################################################################################################################

# Main theme
{80}{}{Arcanum.wav}
# Intro, from 90 to 99
{90}{}{Arcanum.avi}

####################################################################################################################################
#
#       Chat
#
####################################################################################################################################

# On head messages
{100}{}{|0xF8F993 %s}                     # Normal
{102}{}{|0xFF0000 !!!%s!!!}               # Shout
{104}{}{|0xFF00FF **%s**}                 # Emote
{106}{}{|0x00FFFF ...%s...}               # Whisp
{108}{}{|0xFFFFFF %s}                     # Social

# Message box
{120}{}{%s: |0xF8F993 %s}                 # Normal
{122}{}{%s: |0xFF0000 !!!%s!!!}           # Shout
{124}{}{%s: |0xFF00FF **%s**}             # Emote
{126}{}{%s: |0x00FFFF ...%s...}           # Whisp
{128}{}{%s: |0xFFFFFF %s}                 # Social
{130}{}{Рация %u> |0xFFFFFE ..%s..}       # Radio
{132}{}{%s}                               # NetMsg

####################################################################################################################################
#
#       FixBoy
#
####################################################################################################################################

{200}{}{Параметры:}
{201}{}{Инструменты:}
{202}{}{Предметы:}
{205}{}{шт.}
{206}{}{у вас }
{210}{}{Вы успешно создали предмет (ы).}
{211}{}{Вам не удалось создать предмет (ы).}
{212}{}{Вы слишком устали, попробуйте повторить попытку позже.}

####################################################################################################################################
#
#       Interface text
#
####################################################################################################################################

{250}{}{|4291317840 Эта функция сейчас недоступна, используйте FOConfig.exe для редактирования настроек игры.}
{251}{}{Скриншот сохранен.}
{252}{}{Не удалось сохранить скриншот.}
{253}{}{Лог сохранен.}
{254}{}{Не удалось сохранить лог.}

{260}{}{Масштаб %d %%}
{265}{}{Игра приостановлена}

# Dialog
{275}{}{Бартер}
{276}{}{Сказать}
{277}{}{Лог}
# Barter
{280}{}{Обмен}
{281}{}{Диалог}
{282}{}{Выйти}
{283}{}{Сказать}
# Menu
{290}{}{Сохранить}   # Singleplayer
{291}{}{Загрузить}   # Singleplayer
{292}{}{Опции}
{293}{}{Выход}
{294}{}{Продолжить}
# Login
{300}{}{Новая игра}  # Singleplayer
{301}{}{Загрузить}   # Singleplayer
{302}{}{Играть}      # Multiplayer
{303}{}{Регистрация} # Multiplayer
{304}{}{Опции}
{305}{}{Авторы}
{306}{}{Выход}
# Dialog box
{310}{}{Отмена}
{311}{}{Дальше}
{312}{}{Следовать}
{313}{}{Открытый режим}
{314}{}{Скрытый режим}
{315}{}{Реальное время}
{316}{}{Пошаговый режим}
# Reg name
{320}{}{Имя}
{321}{}{Пароль}
# Cha
{325}{}{Далее}
{326}{}{Назад}
{327}{}{Печать}
{328}{}{Навыки}
{329}{}{Очки умений}
# Reg
{335}{}{Особые навыки}
{336}{}{Очки расп.}
# Perk
{340}{}{Взять}
{341}{}{Назад}
# Radio
{345}{}{Канал}
# Global map
{350}{}{Вы не можете управлять группой.}
{351}{}{Координаты: %d : %d\nЗона: %d : %d}
{352}{}{Координаты: %d : %d\nЗона: %d : %d\n%s\n%s}
{353}{}{%s\n%s}
# Aim
{360}{}{Цель заблокирована.}
# Split
{365}{}{Переместить}
{366}{}{Все}
# Timer
{370}{}{Таймер}
# Say screen
{375}{}{Далее}
{376}{}{Назад}
{377}{}{Сказать...}
# Input box
{380}{}{Запись}
{381}{}{Назад}
# Town view
{385}{}{Назад}
{386}{}{Войти}
{387}{}{Контуры}
# Save/Load
{390}{}{Сохранить}
{391}{}{Загрузить}
{392}{}{Далее}
{393}{}{Назад}
{394}{}{Новая запись}
{395}{}{Введите имя записи}

####################################################################################################################################
#
#       Inventory (with INVENTRY.MSG + 400)
#
####################################################################################################################################

{400}{}{СЛ}
{401}{}{СЖ}
{402}{}{ЛВ}
{403}{}{ВН}
{404}{}{ИН}
{405}{}{ВЛ}
{406}{}{ВС}
{407}{}{ОБ}
{408}{}{Класс брони }
{409}{}{  Норма}
{410}{}{  Магия}
{411}{}{  Природа}
{412}{}{  Дух}
{413}{}{  Взрыв}
{414}{}{Нет вещи}
{415}{}{Повр:}
{416}{}{Длн:}
{417}{}{Заряд:}
{418}{}{(Не одето)}
{419}{}{У вас не хватает Очков действия для входа в инвентарь.}
{420}{}{  Общий вес:}
{421}{}{ПЕРЕМЕСТИТЬ}
{422}{}{ВСЕ}
{423}{}{ТАЙМЕР}
{424}{}{Безоружно:}
{425}{}{Вы не можете подобрать эту вещь. Вы и так несете максимальный груз.}
{426}{}{Для этой вещи не хватает места.}
{429}{}{За удачное применение умения воровать, вы получаете %d очков опыта.}
{430}{}{Вес}
{433}{}{Вы не находите там ничего для себя полезного.}
{434}{}{Имеется VALUE/MAX_VALUE зарядов - AMMO.}
{435}{}{Вес: VALUE грамм.}
{436}{}{Вес: VALUE фунтов.}
{437}{}{Цена: VALUE монет.}
{438}{}{Цена у торговца: VALUE монет.}
{440}{}{Перегруз}
{441}{}{Скрытность}
{442}{}{Уровень}
{443}{}{Отравление}
{444}{}{Переохлаждение}
{445}{}{Травмирован}
{446}{}{Привыкание}
{447}{}{Таймаут %u}
{448}{}{Негабаритный}
{449}{}{Ваш ход %u}
{450}{}{Пошагово}
{451}{}{Осталось очков: VALUE}
{452}{}{Жизней}
####################################################################################################################################
#
#       Radio
#
####################################################################################################################################

{460}{}{Началось астральное вещание.}
{461}{}{Астральное вещание закончено.}
{462}{}{Астральный канал сменен.}
{463}{}{Нет астральной сферы.}
{464}{}{Батарея астральной сферы разряжена.}

####################################################################################################################################
#
#       Barter
#
####################################################################################################################################

{480}{}{Ну хорошо, будь по вашему.}
{481}{}{Нет, ваше предложение меня не радует.}
{482}{}{Извините, для вас это уже слишком.}
{483}{}{Извините, но столько вам не унести.}
{484}{}{На момент продажи у вас не было выбранной вещи.}
{485}{}{Извини, но я уже продал кое-что из того, что ты выбрал.}
{486}{}{Вы не можете торговать в данный момент.}
{487}{}{Вы не можете торговать с этим персонажем.}
{490}{}{%s хочет поторговать с вами. Режим торговли: %s.}
{491}{}{открытый}
{492}{}{скрытный}
{493}{}{Игрок не может сейчас торговать с вами.}
{495}{}{Начата торговля с %s. Ваш режим: %s, режим оппонента: %s.}
{496}{}{%s готов к сделке.}

####################################################################################################################################
#
#       Items info
#
####################################################################################################################################

# Wear
{500}{}{Износ: VALUE%.}
{501}{}{Пройдено сервисное обслуживание.}
{502}{}{Пройдено дополнительное сервисное обслуживание.}
{503}{}{Небольшая поломка.}
{504}{}{Поломка средней тяжести.}
{505}{}{Серьезная поломка.}
{506}{}{Восстановлению не подлежит.}
{507}{}{Ломался: VALUE раз.}

{510}{}{Сервисное обслуживание уже пройдено.}
{511}{}{Сервисное обслуживание пройдено успешно.}
{512}{}{Сервисное обслуживание провалено.}
{515}{}{Ремонт произведен успешно.}
{516}{}{Ремонт провален.}

{520}{}{Ваша броня сломалась.}
{521}{}{Ваше оружие сломалось.}

{530}{}{Доспех или одежда не того размера, вы неможете это носить.}

# Key
{550}{}{Ключ номер KEY_ID.}

# Car
{560}{}{Номер машины CAR_ID.}
{561}{}{Топливо: VALUE/MAX_VALUE.}
{562}{}{Износ: VALUE%.}

#ArcReborn custom game text
#combat skills
{570}{}{Лук}
{571}{}{Увертливость}
{572}{}{Рукопашная}
{573}{}{Метание}

{574}{}{Удар в спину}
{575}{}{Воровство}
{576}{}{Ловушки}
{577}{}{Скрытность}

{578}{}{Игра}
{579}{}{Торговля}
{580}{}{Лечение}
{581}{}{Убеждение}

{582}{}{Ремонт}
{583}{}{Взлом}
{584}{}{Огнестрельное оружие}
{585}{}{Наука}

{586}{}{Гид}
{587}{}{Горное дело}
{588}{}{Агроном}
{589}{}{Готовка}
#Arcreborn tech disciplines
#"Anatomical","Chemistry","Electrical","Explosives","GunSmithy","Mechanical","Smithy","Therapeutics"

{590}{}{Гербология}
{591}{}{Химия}
{592}{}{Электричество}
{593}{}{Взрывчатка}
{594}{}{Оружейник}
{595}{}{Механика}
{596}{}{Кузнец}
{597}{}{Терапевтика}

{598}{}{уровень}

#spells names
#group1
{599}{}{Разоружение}
{600}{}{Открывающий кантрип}
{601}{}{Невидимая сила}
{602}{}{Пространственное искажение}
{603}{}{Телепортация}

#group2
{604}{}{Определение характера}
{605}{}{Узнать содержимое}
{606}{}{Исследование ауры}
{607}{}{Увидеть невидимое}
{608}{}{Идентификация}

#group3 air
{609}{}{Энергия воздуха}
{610}{}{Ядовитые пары}
{611}{}{Призвать ветры}
{612}{}{Превратить в воздух}
{613}{}{Воздушный элементаль}

#group4 earth
{614}{}{Сила земли}
{615}{}{Бросок камня}
{616}{}{Каменная стена}
{617}{}{Превратить в камень}
{618}{}{Каменный элементаль}

#group5 fire
{619}{}{Быстрота огня}
{620}{}{Огненная стена}
{621}{}{Огненный шар}
{622}{}{Превратить в огонь}
{623}{}{Огненный элементаль}

#group6 water
{624}{}{Чистота воды}
{625}{}{Туман}
{626}{}{Град}
{627}{}{Превратить в воду}
{628}{}{Водный элементаль}

#group7 force
{629}{}{Защитный экран}
{630}{}{Удар}
{631}{}{Стена света}
{632}{}{Молния}
{633}{}{Дезинтеграция}

#group8 mental
{634}{}{Зачарование}
{635}{}{Оглушение}
{636}{}{Выпить волю}
{637}{}{Кошмар}
{638}{}{Подчинение Воли}

#group9 meta
{639}{}{Определение характера}
{640}{}{Развеять магию}
{641}{}{Двеомерный щит}
{642}{}{Сфера антимагии}
{643}{}{Магическое зеркало}

#group10 morph
{644}{}{Закаленные руки}
{645}{}{Ослабление}
{646}{}{Уменьшение}
{647}{}{Плоть в камень}
{648}{}{Полиморф}

#group11 nature
{649}{}{Зачаровать животное}
{650}{}{Запутывание}
{651}{}{Подчинить животное}
{652}{}{Призвать животное}
{653}{}{Регенерация}

#group12 black necromantic
{654}{}{Вред}
{655}{}{Призыв духа}
{656}{}{Призыв нежити}
{657}{}{Создание нежити}
{658}{}{Призыв фантома}

#group13 white necromantic
{659}{}{Излечение легких ран}
{660}{}{Излечение от яда}
{661}{}{Излечение серьезных ран}
{662}{}{Святилище}
{663}{}{Воскрешение}

#group14 phantazm
{664}{}{Освещение}
{665}{}{Вспышка}
{666}{}{Смазывание }
{667}{}{Призрачный демон}
{668}{}{Невидимость}

#group15 summoning
{669}{}{Рой насекомых}
{670}{}{Призыв орка-чемпиона}
{671}{}{Призыв огра-телохранителя}
{672}{}{Адские врата}
{673}{}{Фамилиар}

#group16 temp
{674}{}{Магический замок}
{675}{}{Замораживание времени}
{676}{}{Ускорение}
{677}{}{Капкан}
{678}{}{Время летит...}
#end of spells group

#begin tech profession
{679){}{Дилетант}
{680){}{Новичок}
{681){}{Ассистент}
{682){}{Кандидат}
{683){}{Техник}
{684){}{Инженер}
{685){}{Профессор}
{686){}{Доктор}

{687}{}{Гербология}
{688}{}{Химия}
{689}{}{Электрика}
{690}{}{Взрывчатые Вещества}
{691}{}{Оружейное Дело}
{692}{}{Механика}
{693}{}{кузнечное Дело}
{694}{}{Терапия}

#end tech profession

####################################################################################################################################
#
#       PipBoy, Timeouts
#
####################################################################################################################################

{700}{}{----- Статус -----}
{701}{}{Баланс репликации}
{702}{}{%d монет}
{703}{}{Стоимость репликации}
{704}{}{%d монет}
{705}{}{Всего репликаций}
{706}{}{%d раз}
{720}{}{----- Квесты -----}
{723}{}{<<<<< Статистика >>>>>}
{725}{}{----- Карты -----}
{730}{}{----- Инфо -----}

{740}{}{----- Таймауты -----}
{741}{}{%s секунд}
{742}{}{%s минут}
{790}{}{Таймаут на переходы. Ждите.}
{791}{}{Боевой таймаут. Ждите.}
{792}{}{Таймаут на скрытность. Ждите.}

{795}{}{Информация в процессе загрузки...}
{796}{}{Ошибка загрузки! Пожалуйста перезагрузите PipBoy.}

####################################################################################################################################
#
#       Dialogs
#
####################################################################################################################################
{797}{}{|4294967295
{800}{}{Вы не можете говорить с мобом.}
{801}{}{Нпц не в состоянии сейчас говорить.}
{802}{}{Нпц занят. Попробуйте поговорить позже.}
{803}{}{Слишком большая дистанция для разговора.}
{804}{}{Привет.} # Нет диалогов.
{805}{}{Нпц разговаривает с другими игроками. Попробуйте поговорить позже.}
{806}{}{Ошибка преддиалоговых настроек.}
{807}{}{Битая ссылка диалога.}
{808}{}{Ошибка компановки диалога.}
{809}{}{Нпц не найден.}
{810}{}{Не валидный указатель на диалог.}

####arcreborn misc
{820}{}{Сила}
{821}{}{Телосложение}
{822}{}{Ловкость}
{823}{}{Внешность}
{824}{}{Интеллект}
{825}{}{Сила Воли}
{826}{}{Восприятие}
{827}{}{Харизма}
{828}{}{СИЛ}
{829}{}{ТЕЛ}
{830}{}{ЛОВ}
{831}{}{ВНЕ}
{832}{}{ИНТ}
{833}{}{ВОЛ}
{834}{}{ВСП}
{835}{}{ХАР}

# arc_message text
{836}{}{Необходимо повысить силу.}
{837}{}{Необходимо повысить телосложение.}
{838}{}{Необходимо повысить ловкость.}
{839}{}{Необходимо повысить внешность.}
{840}{}{Необходимо повысить интеллект.}
{841}{}{Необходимо повысить силу воли.}
{842}{}{Необходимо повысить восприятие.}
{843}{}{Необходимо повысить харизму.}
{844}{}{Нехватает свободных очков.}
{845}{}{Прежде чем понижать основную характеристику, необходимо понизить навыки, которые зависят от этой характеристики.}
{846}{}{Нельзя больше уменьшать данное значение}
{847}{}{Нельзя больше увеличивать данное значение}
{848}{}{Ошибка в параметрах персонажа!}


####################################################################################################################################
#
#       Global map
#
####################################################################################################################################

{900}{}{Вы не нашли локацию, ее поглотила пустошь.}
{901}{}{Локация странным образом переместилась в другое место.}
{902}{}{Вы не нашли входа в локацию.}
{903}{}{Вы не нашли стоянки для своего транспорта.}
{904}{}{Локация переполнена, попробуйте войти позже.}
{950}{}{Вы готовы следовать за %s в %s?}
{952}{}{Приготовьтесь следовать за %s в %s.}
{970}{}{незнакомцем}
{972}{}{пустошь}

####################################################################################################################################
#
#       Maintenance
#
####################################################################################################################################

{1001}{}{|4291317840 Введен неверный логин.}
{1002}{}{|4291317840 Введен неверный пароль.}
{1003}{}{|4291317840 Аккаунт с таким именем уже есть - измените логин.}
{1004}{}{|4291317840 Игрок под этим логином уже в игре.}
{1005}{}{|4291317840 Неверные данные SPECIAL.}
{1006}{}{|4291317840 Регистрация пройдена успешно.}
{1007}{}{|4291317840 Идет соединение с сервером.}
{1008}{}{|4291317840 Сбой соединения! При повторениях сбоя - обратитесь к администратору сервера.}
{1009}{}{|4291317840 Неверный логин или пароль.}
{1010}{}{|4291317840 Соединение установлено, аутентификация...}
{1012}{}{|4291317840 Гексы для высадки заняты, попробуйте войти в игру немного позже.}
{1013}{}{|4291317840 Отключение по команде игрока.}
{1014}{}{|4291317840 Ошибка в имени. Возможно слишком длинное или короткое.}
{1015}{}{|4291317840 Ошибка в одном из склонений имени. Возможно слишком длинное или короткое.}
{1016}{}{|4291317840 Пол введен неверно.}
{1017}{}{|4291317840 Возраст введен неверно.}
{1018}{}{|4291317840 Не удалось подключиться к серверу игры.}
{1019}{}{|4291317840 Введены неверные данные.}
{1020}{}{|4291317840 Ошибка поиска стартовой локации, свяжитесь с администрацией сервера.}
{1021}{}{|4291317840 Ошибка поиска стартовой карты, свяжитесь с администрацией сервера.}
{1022}{}{|4291317840 Ошибка поиска стартовых координат, свяжитесь с администрацией сервера.}
{1023}{}{|4291317840 Ошибка БД, свяжитесь с администрацией сервера.}
{1024}{}{|4291317840 Неверная версия сетевого протокола, обновите клиент.}
{1025}{}{|4291317840 Ошибка в передаче данных, попробуйте еще раз.}
{1026}{}{|4291317840 Неверное сетевое сообщение.}
{1027}{}{|4291317840 Внутренняя ошибка сервера №1, сообщите о ней администрации сервера.}
{1028}{}{|4291317840 Аутентификация пройдена, загрузка карты.}
{1029}{}{|4291317840 Выберите 3 умения.}
{1030}{}{|4291317840 Имя должно быть написано с использованием одного языка.}
{1031}{}{|4291317840 Имя на 70% должно состоять из букв алфавита.}
{1032}{}{|4291317840 Пробел не может быть использован в начале или конце имени.}
{1033}{}{|4291317840 Не допускается ставить в имени два пробела подряд.}
{1034}{}{|4291317840 Ваш аккаунт заблокирован.}
{1035}{}{|4291317840 Недопустимые символы в имени.}
{1036}{}{|4291317840 Недопустимые символы в пароле.}
{1037}{}{|4291317840 Ошибка загрузки пользовательского интерфейса.}
{1038}{}{|4291317840 Ошибка выполнения стартового скрипта.}
{1039}{}{|4291317840 Выбранный язык не поддерживается. Установлен язык по умолчанию.}
{1040}{}{|4291317840 Игра может работать некорректно при разрешениях меньше 800x600 или больше 1280x1024.}
{1041}{}{|4291317840 Тук-тук, кто-нибудь есть?}
{1042}{}{|4291317840 Обнаружены частые регистрации с одного IP адреса. Попробуйте позже.}
{1043}{}{|4291317840 Ваш IP заблокирован.}
{1044}{}{|4291317840 Минимальное время игры с одного компьютера для одного аккаунта составляет 10 минут.}
{1045}{}{|4291317840 Времени осталось: @lex time@ минут.}
{1046}{}{|4291317840 Вы были забанены.}
{1047}{}{|4291317840 Бан от: @lex banby@, Продолжительность: @lex time@ часов, Комментарий: @lex reason@.}
{1048}{}{|4291317840 Ошибка скрипта, обратитесь к администрации сервера.}
{1049}{}{|4291317840 Ваш персонаж полностью умер, игра за данный аккаунт больше невозможна.}

# Singleplayer messages
{1070}{}{|4291317840 Игра сохранена.}
{1071}{}{|4291317840 Ошибка сохранения игры.}
{1072}{}{|4291317840 Игра загружена.}
{1073}{}{|4291317840 Ошибка загрузки игры.}
{1074}{}{|4291317840 Новая игра начата.}
{1075}{}{|4291317840 Ошибка начала новой игры.}

####################################################################################################################################
#
#       Character
#
####################################################################################################################################

#
# STAT LEVEL DESCRIPTIONS
#
{2301}{}{Гадко}
{2302}{}{Плохо}
{2303}{}{Низко}
{2304}{}{Неплохо}
{2305}{}{Средне}
{2306}{}{Xорошо}
{2307}{}{Высоко}
{2308}{}{Отлично}
{2309}{}{Круто}
{2310}{}{Герой!}

#Abbreviated, for editor
{2311}{}{Гадко}
{2312}{}{Плохо}
{2313}{}{Низко}
{2314}{}{Непл.}
{2315}{}{Средн.}
{2316}{}{Xорош.}
{2317}{}{Высок.}
{2318}{}{Отлич.}
{2319}{}{Круто}
{2320}{}{Герой!}

#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{3300}{}{+ (4 х ЛВ)}
{3301}{}{+ (2 х ЛВ)}
{3302}{}{+ (2 х ЛВ)}
{3303}{}{+ (ЛВ + СЛ)х2}
{3304}{}{+ (ЛВ + СЛ)х2}
{3305}{}{+ (4 х ЛВ)}
{3306}{}{+ (ВС + ИН)х2}
{3307}{}{+ (ВС + ИН)}
{3308}{}{+ (3 х ЛВ)}
{3309}{}{+ (ВС + ЛВ)}
{3310}{}{+ (3 х ЛВ)}
{3311}{}{+ (ВС + ЛВ)}
{3312}{}{+ (4 x ИН)}
{3313}{}{+ (3 х ИН)}
{3314}{}{+ (5 x ОБ)}
{3315}{}{+ (4 x ОБ)}
{3316}{}{+ (5 x УД)}
{3317}{}{+ (ВН + ИН)х2}
#
# SKILLDEX
#
{3340}{}{УМЕНИЯ}
{3341}{}{ОТКАЗ}

#
#   Skill Use Text
#
{3400}{}{Вы пока не воскрешаете мертвых.}
{3400}{}{Пусть мертвые почиют с миром.}
{3400}{}{Не тронь дохляков.}
{3401}{}{Подождите немного, похоже, вы исчерпали себя.}
{3401}{}{Вы слишком устали.}
{3401}{}{Такое напряжение убьет вас.}
{3402}{}{Вы не нуждаетесь в помощи санитара.}
{3403}{}{Вы не нуждаетесь в помощи доктора.}
{3404}{}{Для лечения травмы требуется навык доктора.}
{3405}{}{Для лечения этих повреждений требуется навык первой помощи.}

{3412}{}{Вы лечите раненый глаз.}
{3413}{}{Вы лечите сломанную правую руку.}
{3414}{}{Вы лечите сломанную левую руку.}
{3415}{}{Вы лечите сломанную правую ногу.}
{3416}{}{Вы лечите сломанную левую ногу.}
{3422}{}{Вы не лечите раненый глаз.}
{3423}{}{Вы не лечите сломанную правую руку.}
{3424}{}{Вы не лечите сломанную левую руку.}
{3425}{}{Вы не лечите сломанную правую ногу.}
{3426}{}{Вы не лечите сломанную левую ногу.}

{3430}{}{Вас пытались обокрасть!}
{3431}{}{Вам пытались что-то подложить!}

{3440}{}{Попытка взлома безуспешна.}
{3441}{}{Вы не смогли устновить ловушку.}
{3442}{}{Вы устанавливаете ловушку.}
{3443}{}{Вы не смогли снять ловушку.}
{3444}{}{Вы смогли разминировать ловушку.}
{3445}{}{Вы не можете войти в режим скрытности, когда вас кто-нибудь видит.}

{3450}{}{Вы прибавили %d очков жизней.}
{3451}{}{Вы и без того здоровы.}
{3452}{}{%s и без того выглядит неплохо.}
{3453}{}{Попытка лечения не удалась.}
{3455}{}{Вы получаете %d Опыта за использование умений.}
{3459}{}{\nskill_use: неправильное умение.}
{3461}{}{Вы не видите ловушек.}
{3462}{}{Вы так ничего и не узнали.}
{3463}{}{Ремонту не подлежит.}
{3470}{}{Вам не удалось похитить %s.}
{3471}{}{Вы похищаете %s.}
{3472}{}{Вы не сумели установить %s.}
{3473}{}{Вы устанавливаете %s.}
{3495}{}{Вы не так умелы, чтобы излечивать настолько тяжелые раны.}
{3496}{}{Починить этого робота невозможно.}

#
#    PC STAT NAMES
#
{4000}{}{Пункты}
{4001}{}{Следующий уровень}
{4002}{}{Осталось пунктов}
{4003}{}{Уровень}
{4004}{}{Опытность}
{4005}{}{Репутация}
{4006}{}{Карма}
{4007}{}{Бонусы}
{4008}{}{Убито}
{4009}{}{Очки умений}
{4010}{}{Способности}
{4011}{}{Дополнительно}
{4012}{}{Умения}
#
#    PC STAT DESCRIPTIONS
#
{4050}{}{Количество очков, оставшихся для добавления к одной из базовых характеристик персонажа.}
{4051}{}{Количество очков опыта, необходимых для получения следующего уровня.}
{4052}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}
{4053}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
{4054}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
{4055}{}{Известная миру информация о ваших деяниях, их оценка в народе. Влияет на прием вашего героя.}
{4056}{}{Эффект от предпринятых вами действий за время игры.}
{4057}{}{Бонусы прибавляют дополнительные способности. За каждый третий уровень опыта вы получаете один бонус.}
{4058}{}{Количество существ, погибших в вашем присутствии от естественных причин, как-то автоматных очередей, взрывов гранат и огнеметных залпов.}
{4059}{}{Увеличивайте свои умения распределением очков.}
{4060}{}{Вы обязаны выбрать три способности, в которых будет специализироваться ваш персонаж. За каждую он получит бонус 20%, а повышаться они будут вдвое быстрее.}
{4061}{}{Дополнительные способности описывают вашего персонажа более подробно. Все они имеют свои положительные и отрицательные стороны. Во время создания можно выбрать максимум две.}
{4062}{}{Умения накапливаются с опытом и изучением, а, кроме того, во время разных событий по игре. Чем выше те или иные умения, тем больше вероятность ваших успешных действий.}

#
#  Experience-gain messages
#
{4090}{}{Вы получили новый уровень.}
{4091}{}{Вы получили VALUE опыта.}
{4092}{}{Вы получили %d очков опыта за убийство существа : %s.}
{4093}{}{%s вы получили %d очков опыта.}
{4094}{}{За победу над врагами, }  # 622-626 prepend to line 621
{4095}{}{За уничтожение противника, }
{4096}{}{Вы победили в этом бою, }
{4097}{}{За разгром ваших врагов }
{4098}{}{За уничтожение противника без единой царапины, }

#
# Editor
#
{4104}{}{ЛЕТ}
{4105}{}{ПОЛ}
{4106}{}{ИМЯ}
{4107}{}{МУЖ.}
{4108}{}{ЖЕН.}
{4109}{}{БОНУСЫ}
{4110}{}{КАРМА}
{4111}{}{УБИТО}
{4112}{}{ОЧКИ УМЕНИЙ}
{4113}{}{Уровень: %d}
{4114}{}{Опыт: %d}
{4115}{}{След. ур.: %d}

#
# Damage info texts
#

{4250}{}{Жизни  %d/%d}

#
# Karma
#

{6000}{}{Карма}
{6001}{}{: %d (%s)}  # Value, Desc
{6002}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

{6099}{}{9} # Max values
{6100}{}{1000} # Min value
{6101}{}{Спаситель обреченных} # Desc
{6102}{}{2000} # Picture index
{6103}{}{750}
{6104}{}{Надежда пустыни}
{6105}{}{2001}
{6106}{}{500}
{6107}{}{Щит надежды}
{6108}{}{2002}
{6109}{}{250}
{6110}{}{Защитник}
{6111}{}{2003}
{6112}{}{-249}
{6113}{}{Странник}
{6114}{}{2004}
{6115}{}{-500}
{6116}{}{Нечисть}
{6117}{}{2005}
{6118}{}{-750}
{6119}{}{Омраченная душа}
{6120}{}{2006}
{6121}{}{-1000}
{6122}{}{Бич пустоши}
{6123}{}{2007}
{6124}{}{-2147483648}
{6125}{}{Дьявольское отродье}
{6126}{}{2008}

#
# Town reputation
#

{6405}{}{Репутация}
{6406}{}{Отмечает вашу репутацию среди жителей разных поселений.}

# Name
{6500}{}{Поклонение}
{6501}{}{Любовь}
{6502}{}{Симпатия}
{6503}{}{Апатия}
{6504}{}{Скука}
{6505}{}{Злоба}
{6506}{}{Ярость}

# Desc
{6550}{}{Каждый человек отсюда стремится хоть немного походить на вас. Вас носят на руках, прославляют в стихах и песнях и называют детей в вашу честь.}
{6551}{}{Когда вы здесь появляетесь, люди радостно приветствуют вас. Все они что-нибудь слышали о вас и желают вам всего самого наилучшего.}
{6552}{}{Xотя никто не бросается вас обнимать, как только увидит, местные жители хорошо к вам относятся. У них сложилось в целом приятное о вас впечатление.}
{6553}{}{Несмотря на подозрительное отношение к незнакомым людям, вы ни у кого не вызываете ни положительных, ни отрицательных эмоций.}
{6554}{}{Появившийся неизвестно откуда чужак - так думают все и ждут от вас какой-либо каверзы.}
{6555}{}{Своим поведением вы доказали, что вас подозревали не зря. Увидев вас, люди начинают перешептываться и показывать пальцем, как будто на внезапно объявившегося сборщика налогов.}
{6556}{}{С опаской поглядывая в вашу сторону, местные жители обходят вас за километр, плюют вам в спину и отворачиваются при попытке заговорить. Всем известно, что хуже и гаже вас никого нет.}

#
# Addiction title
#

{6900}{}{Привычки}
{6901}{}{Возникшие у вас вредные привычки.}


####################################################################################################################################
#
#       Items games
#
####################################################################################################################################

# Сообщение в мессаджбокс при наведении на объект
{10000}{}{Вы видите: NAME.}
# При рассмотрении объекта
{10004}{}{NAME}
# Имя или инфо не найдено
{10010}{}{Вы не видите ничего необычного.}
# Item not found in container (possible another critter take it)
{10020}{}{Предмет не найден, возможно его взял кто-то другой.}

# Container
{10100}{}{Закрыто.}
{10101}{}{Вы обыскали %s.}
{10102}{}{Вы закрыли %s.}

#
# Use text messages
#
{10200}{}{Вы применили: %s.}
{10201}{}{Вы применили: %s на %s.}
{10202}{}{Из этого ничего не вышло.}
{10203}{}{К своей досаде, вы догадались, что перед вами обычный труп.}
{10204}{}{Когда вы нагнулись и посмотрели, то обнаружили мертвое тело.}
{10205}{}{Жаль, но вы опоздали.}
{10206}{}{Это все как мертвому припарки.}
{10207}{}{Вы засветили фонарь.}
{10208}{}{Фонарь уже зажжен.}
{10209}{}{Вы установили таймер.}
{10210}{}{Таймер давно начал работу!}
{10211}{}{Вход кажется заблокирован.}
# Solar scotcher
{10240}{}{Вы не можете перезарядить батарейки - не хватает света.}
# Car
{10250}{}{Вы подзарядили машину энергией.}
{10251}{}{Энергоблок машины уже полностью заряжен.}
{10252}{}{Вы успешно отремонитровали машину.}
{10253}{}{Машина не нуждается в ремонте.}
{10254}{}{Этот двигатель не работает на данном виде топлива.}
{10255}{}{Кончилось топливо.}
{10256}{}{Машина сломана.}
{10257}{}{Машина не рассчитана на такое количество людей, уберите лишних.}
{10258}{}{Ваша харизма не позволяет руководить таким количеством людей, уберите лишних.}
{10259}{}{Нельзя отсоединять от группы находясь на воде.}
# Drugs
{10300}{}{Вы получили @lex value@ @lex name@.}
{10301}{}{Вы потеряли @lex value@ @lex name@.}
{10302}{}{Вы чувствуете облегчение.}
{10303}{}{Вы получили инфаркт от чрезмерной передозировки химикалий.}
{10304}{}{По-видимому, ничего не происходит.}
{10305}{}{%s корчится от воздействия различных химикалий.}
{10306}{}{На вас применили какой-то наркотик!}
{10307}{}{На вас пытались применить какой-то наркотик!}
# Geiger
{10350}{}{У счетчика Гейгера кончились заряды.}
{10351}{}{Счетчик Гейгера включен.}
{10352}{}{Счетчик Гейгера выключен.}
{10353}{}{Вы провели счетчик Гейгера над своим телом. На табло появились цифры: @lex rem@.}
{10354}{}{На табло появились цифры: @lex rem@.}
{10355}{}{Ничего не происходит.}
{10356}{}{Счетчик Гейгера подзаряжен.}
{10357}{}{Счетчик Гейгера заряжен на @lex cur@/@lex max@.}
# Weapon Damage
{10400}{}{Легк.}
{10401}{}{Средн.}
{10402}{}{Тяжел.}
{10403}{}{Экстрем.}
# Weapon Range
{10410}{}{Корот.}
{10411}{}{Средн.}
{10412}{}{Дальн.}
# Books
{10450}{}{Вы прочитали книгу.}
{10451}{}{Вы не узнали ничего нового.}
{10452}{}{Вы уяснили новую научную информацию.}
{10453}{}{Вы многое поняли о способах починки сломанной электроники.}
{10454}{}{Вы узнали новые способы обработки ран.}
{10455}{}{Вы научились лучше обращаться с оружием.}
{10456}{}{Вы научились лучше обращаться с энергетическим оружием.}
{10457}{}{Вы изучили новые способы выживания в пустыне.}
# Use on
{10500}{}{Запасы в Сумке Доктора подошли к концу.}
{10501}{}{Запасы в Аптечке Первой помощи подошли к концу.}
{10502}{}{Запрещено делать это во время боя.}
{10503}{}{Этот персонаж не будет торговать с вами.}
{10504}{}{Этот персонаж ничего вам не собирается говорить.}
{10505}{}{Вы не подберете этот предмет. Вы и так слишком нагружены разными вещами.}
{10506}{}{Медикаменты в Санитарной Сумке подошли к концу.}
{10507}{}{Запасы лекарств в Армейской Полевой Аптечке истощились.}
{10508}{}{Это существо не может ничего нести.}
# Grave
{10550}{}{Эта могила разрыта.}
{10551}{}{Эта могила зарыта.}

####################################################################################################################################
#
#       Calibers (from PROTO.MSG)
#
####################################################################################################################################

#
# Caliber Types for weapons
#
{10900}{}{Нету}
{10901}{}{Ракета}
{10902}{}{Топливо огнемета}
{10903}{}{Энергопак С}
{10904}{}{Энергопак Д}
{10905}{}{.223}
{10906}{}{5мм}
{10907}{}{.40 кал.}
{10908}{}{10мм}
{10909}{}{.44 кал.}
{10910}{}{14мм}
{10911}{}{Дробь}
{10912}{}{9мм}
{10913}{}{ББ}
{10914}{}{.45 кал.}
{10915}{}{2мм}
{10916}{}{Обойма 4.7мм}
{10917}{}{Основные XН}
{10918}{}{7.62мм}
{10919}{}{.700 Найтро Экспресс}

####################################################################################################################################
#
#       Critters game
#
####################################################################################################################################

#
#   Male
#

##First words
#For age and conditions
{11000}{}{Вы видите }
{11001}{}{Это вы }
#For special
{11002}{}{На вид }
#For damages
{11003}{}{У него }

#Self look
{11005}{}{Опа, это же ты.}
{11005}{}{Какие люди в голливуде.}
{11005}{}{Кто же это?}
{11005}{}{Чувак, ты им можешь управлять.}
{11005}{}{Перестань меня разглядывать!!!}

#Default view
{11010}{}{Вы видите: NAME.}
{11011}{}{Вы видите лежачего: NAME.}
{11012}{}{Вы видите труп: NAME.}
{11013}{}{Вы видите останки: NAME.}
{11014}{}{Вы не видите ничего необычного.}

##Age, max age 99
#<=16
{11116}{}{пацана}
#<=30
{11130}{}{молодого человека}
#<=40
{11140}{}{мужчину средних лет}
#<=60
{11160}{}{пожилого мужчину}
#>60
{11199}{}{старика}

##Conditions
#Prepare to fight
{11212}{}{его тело странно напряжено, он готов атаковать в любую секунду}
#Knock out face up
{11221}{}{он лежит на земле, явно не загорает}
#Knock out face down
{11222}{}{он решил поспать}
#Dead normal face up
{11231}{}{он немного мертв}
#Dead normal face down
{11232}{}{по ходу, мертв}

##Special
#S
{11301}{}{хилый}
{11302}{}{хлипкий}
{11303}{}{слабый}
{11308}{}{силен}
{11309}{}{очень силен}
{11310}{}{очень силен}
#P
#E
{11321}{}{хрупкого телосложения}
{11322}{}{хрупкого телосложения}
{11325}{}{среднего телосложения}
{11326}{}{среднего телосложения}
#C
{11331}{}{невзрачный}
{11332}{}{невзрачный}
{11333}{}{невзрачный}
{11337}{}{привлекательный}
{11338}{}{обворожительный}
{11339}{}{общительный}
{11340}{}{очень обаятельный}
#I
{11341}{}{тупорылый}
{11342}{}{тупоумный}
{11343}{}{слабоумный}
{11347}{}{интеллектуал}
{11348}{}{интеллектуал}
{11349}{}{гений}
{11350}{}{гениальная личность}
#A
{11351}{}{неуклюжий}
{11352}{}{неуклюжий}
{11357}{}{спортсмен}
{11358}{}{акробат}
{11359}{}{очень ловкий}
{11360}{}{очень ловкий}
#L
{11361}{}{несчастный}
{11362}{}{несчастливый}
{11363}{}{несчастливый}
{11368}{}{веселый}
{11369}{}{энтузиаст}
{11370}{}{очень удачливый}

##Damages
#Poisoned
{11400}{}{странные волдыри на коже}
#Radiated
{11401}{}{тело непонятно светиться}
#Eyes
{11402}{}{повреждены глаза}
#Right Arm
{11403}{}{вся правая рука в крови}
#Left Arm
{11404}{}{из левой руки хлещет кровь}
#Right Leg
{11405}{}{похоже сломана правая нога}
#Left Leg
{11406}{}{левая нога сильно повреждена}

#
#   Female
#

##First words
#For age and conditions
{12000}{}{Вы видите }
{12001}{}{Это вы }
#For special
{12002}{}{На вид }
#For damages
{12003}{}{У нее }

#Self look
{12005}{}{Епт, этож ты.}
{12005}{}{Какие люди в голливуде.}
{12005}{}{Кто же это?}
{12005}{}{Перестань меня разглядывать!!!}
{12005}{}{А я секси. Да?}

##Age, max age 99
#<=16
{12116}{}{девочку}
#<=30
{12130}{}{девушку}
#<=40
{12140}{}{женщину средних лет}
#<=60
{12160}{}{пожилую женщину}
#>60
{12199}{}{старуху}

##Conditions
#Prepare to fight
{12212}{}{ее тело странно напряжено, она готова атаковать в любую секунду}
#Knock out face up
{12221}{}{она лежит на земле, явно не загорает}
#Knock out face down
{12222}{}{она решила поспать}
#Dead normal face up
{12231}{}{она немного мертва}
#Dead normal face down
{12232}{}{по ходу, мертва}

##Special
#S
{12301}{}{хилая}
{12302}{}{хлипкая}
{12303}{}{слабая}
{12308}{}{сильная}
{12309}{}{очень сильна}
{12310}{}{очень сильна}
#P
#E
{12321}{}{хрупкого телосложения}
{12322}{}{хрупкого телосложения}
{12325}{}{среднего телосложения}
{12326}{}{среднего телосложения}
#C
{12331}{}{невзрачная}
{12332}{}{невзрачная}
{12333}{}{невзрачная}
{12337}{}{привлекательная}
{12338}{}{обворожительная}
{12339}{}{общительная}
{12340}{}{очень обаятельная}
#I
{12341}{}{тупорылая}
{12342}{}{тугоумная}
{12343}{}{слабоумная}
{12347}{}{интеллектуал}
{12348}{}{интеллектуал}
{12349}{}{гений}
{12350}{}{гениальная личность}
#A
{12351}{}{неуклюжая}
{12352}{}{неуклюжая}
{12357}{}{спортсменка}
{12358}{}{акробатка}
{12359}{}{очень ловкая}
{12360}{}{очень ловкая}
#L
{12361}{}{несчастная}
{12362}{}{несчастливая}
{12363}{}{несчастливая}
{12368}{}{веселая}
{12369}{}{энтузиастка}
{12370}{}{очень удачливая}

##Damages
#Poisoned
{12400}{}{странные волдыри на коже}
#Radiated
{12401}{}{тело непонятно светиться}
#Eyes
{12402}{}{повреждены глаза}
#Right Arm
{12403}{}{вся правая рука в крови}
#Left Arm
{12404}{}{из левой руки хлещет кровь}
#Right Leg
{12405}{}{похоже сломана правая нога}
#Left Leg
{12406}{}{левая нога сильно повреждена}

#
# Without awareness: 0 + 1 + [2]
# With awareness: 3 + [2] + [4]
#
{12500}{}{Объект }   # Male
{12501}{}{Объект }   # Female
{12502}{}{Объект }   # It
{12510}{}{мертв}               # Dead condition
{12511}{}{почти мертв}         # <34% hp
{12512}{}{тяжело ранен}        # <67% hp
{12513}{}{ранен}               # <100% hp
{12514}{}{целехонек}           # 100% hp
{12520}{}{есть поврежденные органы}      # Male hurt
{12521}{}{, но есть поврежденные органы} # Male unhurt
{12522}{}{есть поврежденные органы}      # Female hurt
{12523}{}{, но есть поврежденные органы} # Female unhurt
{12524}{}{есть поврежденные органы}      # It hurt
{12525}{}{, но есть поврежденные органы} # It unhurt
{12530}{}{У него есть CUR/MAX жизней} # Male
{12531}{}{У нее есть CUR/MAX жизней}  # Female
{12532}{}{Оно имеет CUR/MAX жизней}   # It
{12540}{}{ и носит при себе WEAPON}                        # Gun without holder
{12541}{}{ и носит при себе WEAPON с CUR/MAX зарядов AMMO} # Gun with holder
{12542}{}{ и носит при себе MISC}                          # Any other item

#
# Other
#

{12600}{}{Ваш криттер не может передвигаться.}

####################################################################################################################################
#
#       Plagues
#
####################################################################################################################################

{12800}{}{Вы чувствуете тошноту.}
{12801}{}{Вы чувствуете тошноту, и после нескольких приступов рвоты сильно утомляетесь.}
{12802}{}{Вы сильно устали, но приступы рвоты не прекращаются, и вы еще долго не можете прийти в себя.}
{12803}{}{У вас кровь идет горлом, выпадают волосы и облезает кожа на открытых участках тела. }
{12804}{}{У вас кровь идет горлом, выпадают волосы и со всего тела отваливается кожа. Рвота не прекращается. Вам не стоило увлекаться работой под Вин95.}
{12805}{}{Все внутренние органы кровоточат, у вас сильный понос и непрекращающаяся рвота. Вы корчитесь от боли и призываете смерть.}
{12806}{}{Вы скончались от лучевой болезни.}
{12807}{}{Вы получили большую дозу радиации.}
{12808}{}{Счетчик Гейгера отметил наличие радиации.}
{12809}{}{Счетчик Гейгера как будто взбесился.}
{12810}{}{Вы ощущаете действие яда!}
{12811}{}{Вы страдаете от отравления.}
{12812}{}{Вы чувствуете себя немного лучше.}
{12813}{}{Вам сильно полегчало.}

####################################################################################################################################
#
#       Scores
#
####################################################################################################################################

{13000}{}{Герои на час}
{13001}{}{Злодей на час (минимальная  значение кармы)}
{13011}{}{Герой на час (максимальное значение кармы)}
{13021}{}{Событие часа (максимальное изменение кармы за последний час)}

{13030}{}{Передовики}
{13031}{}{Почетный оратор (cамый говорливый)}
{13041}{}{Почетный торговец (cамый оборотистый)}
{13051}{}{Почетный зомби (cамый убиваемый)}
{13061}{}{Почетный обаяшка (cамый ветренный)}
{13071}{}{Почетный маньяк (cамый неадекватный)}
{13081}{}{Почетный скаут (cамый мобильный)}
{13091}{}{Почетный Айболит (cамый человеколюбивый)}
{13101}{}{Почетный стрелок (cамый огнестрельный)}
{13111}{}{Почетный клинок (cамый колюще-режущий)}
{13121}{}{Почетный кулак (cамый драчливый)}
{13131}{}{Почетный вор (cамый вороватый)}

{13140}{}{Профессионалы}
{13141}{}{Перевозчик (больше всего людей перевезено)}
{13151}{}{Убийца (больше всего существ убито)}
{13161}{}{Снайпер (больше всего критических попаданий)}
{13171}{}{Искатель приключений (больше всего квестов пройдено)}
{13181}{}{Взломщик (больше всего удачных взломов)}
{13191}{}{Костолом (больше всего рукопашных повреждений)}
{13201}{}{Нувориш (больше всего денег)}

{13210}{}{Избранный}
{13211}{}{Избранный (cамый cамый)}

{13400}{}{Базы}
{13401}{}{Текущий хозяин базы Сиерра}
{13411}{}{Текущий хозяин базы Марипоза}
{13421}{}{Текущий хозяин Собора}
{13431}{}{Лучший хозяин базы Сиерра}
{13441}{}{Лучший хозяин базы Марипоза}
{13451}{}{Лучший хозяин Собора}
{13461}{}{Принадлежность базы Сиерра}
{13471}{}{Принадлежность базы Марипоза}
{13481}{}{Принадлежность Собора}
{13491}{}{Большее предпочтение отдано организации}

####################################################################################################################################
#
#       Stats (with STAT.MSG + 2000)
#
####################################################################################################################################


# ST_STRENGTH
{100001}{}{Сила}
{100002}{}{Грубая физическая сила. Хорошо подходит для воинов и им подобных. Оказывает влияние на Очки Жизней, наносимые Повреждения и Переноску Груза.}

# ST_PERCEPTION
{100011}{}{Восприятие}
{100012}{}{Способность иначе видеть, слышать, замечать и предчувствовать события. Необходимое качество для каждого снайпера. Оказывает влияние на Дальность стрельбы и Порядок действий.}
# ST_ENDURANCE
{100021}{}{Выносливость}
{100022}{}{Выносливость помогает переносить тяготы и лишения судьбы героя с подобающим спокойствием. Оказывает влияние на Очки Жизней, Устойчивость к Яду и Радиации, Уровень Лечения и др.}
# ST_CHARISMA
{100031}{}{Обаяние}
{100032}{}{Обаяние представляет собой комбинацию внешности и шарма. Высокое обаяние необходимо для тех персонажей, которые думают всего добиться словами. Влияет на реакцию людей и цены товаров.}
# ST_INTELLECT
{100041}{}{Интеллект}
{100042}{}{Интеллект отвечает за память, скорость реакции и способность оценивать события. Высокий Интеллект важен для всех. Влияет на количество новых умений-на-уровень, режимы диалога и многие способности.}
# ST_AGILITY
{100051}{}{Ловкость}
{100052}{}{Ловкость и координация движений не раз спасут вас от верной гибели. Каждый активный герой нуждается в ловкости. Влияет на Очки движения, Класс брони, Порядок действий и пр.}
# ST_LUCK
{100061}{}{Сила воли}
{100062}{}{Влияет на количество единиц здоровья и энергии, также от нее зависит количество известных вам заклинаний.}
# ST_MAX_LIFE
{100071}{}{Максимум очков жизней}
{100072}{}{Определяет, какое количество повреждений сможет вынести персонаж, прежде чем умрет. Если Очки Жизни составляют от 0 до –20, персонаж падает на землю и не может двигаться (персонаж не умирает, а начинает восстанавливать запас здоровья, как если бы он отдыхал), но отравленный персонаж умирает даже с 0 Очков Жизни.}
# ST_ACTION_POINTS
{100081}{}{Максимум очков действия}
{100082}{}{Лимит возможных действий, предпринимаемых персонажем. В режиме реального времени Очки Действия восстанавливаются за 7 секунд, в пошаговом они восстанавливаются в начале каждого хода.}
{100083}{}{Очки действий}
# ST_ARMOR_CLASS
{100091}{}{Класс брони}
{100092}{}{Влияет на вероятность поранить данного конкретного персонажа.}
{100093}{}{Класс брони}
# ST_MELEE_DAMAGE
{100101}{}{Рукопашные повреждения}
{100102}{}{Количество повреждений, причиняемых вашим персонажем в рукопашном бою.}
{100103}{}{Рукоп. повр.}
# ST_CARRY_WEIGHT
{100111}{}{Переносимый груз}
{100112}{}{Максимальный вес поклажи, который может переносить ваш персонаж, в фунтах (373 гр. по Тр.)}
{100113}{}{Макс. груз}
# ST_SEQUENCE
{100121}{}{Порядок}
{100122}{}{Определяет порядок начала активных действий вашего персонажа.}
{100123}{}{Порядок}
# ST_HEALING_RATE
{100131}{}{Уровень лечения}
{100132}{}{В конце дня, ваш персонаж будет добавлять по 1 жизни для каждого очка Уровня лечения. Во время отдыха вы лечитесь каждые шесть часов.}
{100133}{}{Уров. лечен.}
# ST_CRITICAL_CHANCE
{100141}{}{Шанс критического удара}
{100142}{}{Вероятность нанесения критических повреждений противнику определяется этим значением.}
{100143}{}{Шанс на крит.}
# ST_MAX_CRITICAL
{100151}{}{Лучшие крит. удары}
{100152}{}{Лучшие крит. удары}
# ST_NORMAL_ABSORB
{100161}{}{Количество повреждений}
{100162}{}{Количество повреждений}
# ST_LASER_ABSORB
{100171}{}{Количество повреждений Магия}
{100172}{}{Количество повреждений Магия}
# ST_FIRE_ABSORB
{100181}{}{Количество повреждений Огонь}
{100182}{}{Количество повреждений Огонь}
# ST_PLASMA_ABSORB
{100191}{}{Количество повреждений Природа}
{100192}{}{Количество повреждений Природа}
# ST_ELECTRO_ABSORB
{100201}{}{Количество повреждений Электр.}
{100202}{}{Количество повреждений Электр.}
# ST_EMP_ABSORB
{100211}{}{Количество повреждений ЭМИ}
{100212}{}{Количество повреждений ЭМИ}
# ST_EXPLODE_ABSORB
{100221}{}{Количество повреждений Взрыв}
{100222}{}{Количество повреждений Взрыв}
# ST_NORMAL_RESIST
{100231}{}{Устойчивость к повреждениям}
{100232}{}{Все получаемые повреждения уменьшаются в соответствии с данным значением. На него сильно влияет Класс брони.}
{100233}{}{Уст. к повр.}
# ST_LASER_RESIST
{100241}{}{Устойчивость к поврежд. Магия}
{100242}{}{Устойчивость к поврежд. Магия}
# ST_FIRE_RESIST
{100251}{}{Устойчивость к поврежд. Огонь}
{100252}{}{Устойчивость к поврежд. Огонь}
# ST_PLASMA_RESIST
{100261}{}{Устойчивость к поврежд. Природа}
{100262}{}{Устойчивость к поврежд. Природа}
# ST_ELECTRO_RESIST
{100271}{}{Устойчивость к поврежд. Электр.}
{100272}{}{Устойчивость к поврежд. Электр.}
# ST_EMP_RESIST
{100281}{}{Устойчивость к поврежд. ЭМИ}
{100282}{}{Устойчивость к поврежд. ЭМИ}
# ST_EXPLODE_RESIST
{100291}{}{Устойчивость к поврежд. Взрыв}
{100292}{}{Устойчивость к поврежд. Взрыв}
# ST_RADIATION_RESISTANCE
{100301}{}{Устойчивость к радиации}
{100302}{}{Количество радиационного облучения, которому вы подвергаетесь, зависит от этого значения. На него влияет тип одетой вами брони и прием антирадиационных химикатов.}
{100303}{}{Уст. к рад.}
# ST_POISON_RESISTANCE
{100311}{}{Устойчивость к яду}
{100312}{}{Уменьшает повреждения от отравления.}
{100313}{}{Уст. к яду}

# 100700
# ST_AGE
{100701}{}{Возраст}
{100702}{}{Возраст}
# ST_GENDER
{100711}{}{Пол}
{100712}{}{Пол}
# ST_CURRENT_HP
{100721}{}{Текущие очки жизней}
{100722}{}{Текущие очки Жизней}
# ST_POISONING_LEVEL
{100731}{}{Текущий уровень яда}
{100732}{}{Текущий уровень Яда}
{100733}{}{Тек. ур. яда}
# ST_RADIATION_LEVEL
{100741}{}{Текущий уровень радиации}
{100742}{}{Текущий уровень Радиации}
{100743}{}{Тек. ур. рад.}

# 100760
# ST_EXPERIENCE
{100761}{}{Опыт}
{100762}{}{Вознаграждение за выполнение определенных задач или победу в схватке с врагами. Для получения высоких уровней необходимо совершенствовать опыт.}
# ST_LEVEL
{100771}{}{Уровень}
{100772}{}{Общая компетентность вашего персонажа. Изменяется в зависимости от полученного вами опыта.}
# ST_UNSPENT_SKILL_POINTS
{100781}{}{Осталось очков умений}
{100782}{}{Количество очков, полученных при повышении уровня. Можно увеличить умение на 1%, или способность на 2% за потраченное очко.}

# 100800
# ST_KARMA
{100801}{}{Карма}
{100802}{}{Этот параметр отвечает за вашу репутацию. Чем он выше, тем лучше к вам будут относиться хорошие персонажи и мирные жители. С отрицательной репутацией все будут вас ненавидеть.}

# 112, ST_BASE_CRTYPE
{101121}{}{Тип тела}

# 150..165, 3d layers
{101501}{}{Кожа}
{101511}{}{Правая рука}
{101521}{}{Левая рука}
{101531}{}{Тело}
{101541}{}{Ноги}
{101551}{}{Руки}
{101561}{}{Голова}
{101571}{}{Волосы}
{101581}{}{Глаза}
{101591}{}{Усы}
{101601}{}{Коса}
{101611}{}{Борода}
{101621}{}{Наплечники}
{101631}{}{Браслет}
{101641}{}{Спина}
{101651}{}{Рюкзак}

####################################################################################################################################
#
#       Skills (with SKILL.MSG + 3000)
#
####################################################################################################################################

# 102000
# SK_SMALL_GUNS
{102001}{}{Огнестрельное оружие}
{102002}{}{Способность управляться с технологическим оружием револьверы, винтовки.}
# SK_BIG_GUNS
{102011}{}{Магия}
{102012}{}{Умение обращаться с магическими сферами и предметами той или иной школы магии.}
# SK_ENERGY_WEAPONS
{102021}{}{Механическое оружие}
{102022}{}{Способность применять гарпуны, луки и арбалеты.}
# SK_UNARMED
{102031}{}{Рукопашная}
{102032}{}{Вероятность нанести успешный удар голыми руками.}
# SK_MELEE_WEAPONS
{102041}{}{Xолодное оружие}
{102042}{}{Использование всего, что может служить оружием ближнего боя: кувалды, ножи, мечи, дубины, топоры.}
# SK_THROWING
{102051}{}{Метание}
{102052}{}{Способность бросать ножи, камни, гранаты и любые другие предметы.}
# SK_FIRST_AID
{102061}{}{Уклонение}
{102062}{}{способность вашего персонажа уворачиваться от ударов}
{102063}{}{Уклонение}
# SK_DOCTOR
{102071}{}{Доктор}
{102072}{}{Излечение тяжелых ранений и умение обращаться с поврежденными частями тела. Без этой способности для излечения будет требоваться очень много времени.}
{102073}{}{Доктор}
# SK_SNEAK
{102081}{}{Умение красться}
{102082}{}{Умение скрываться и передвигаться тихо, чтобы избежать обнаружения.}
{102083}{}{Красться}
# SK_LOCKPICK
{102091}{}{Взлом}
{102092}{}{Навык открывания замков, без использования ключей.}
{102093}{}{Взлом}
# SK_STEAL
{102101}{}{Воровство}
{102102}{}{Способность незаметно вытаскивать вещи из карманов людей (и подкладывать их туда при необходимости).}
{102103}{}{Кража}
# SK_TRAPS
{102111}{}{Установка ловушек}
{102112}{}{Умение работы с ловушками и взрывоопасными устройствами.}
{102113}{}{Ловушки}
# SK_SCIENCE
{102121}{}{Наука}
{102122}{}{Большое количество научного знания, включая биологию, физику и геологию.}
{102123}{}{Наука}
# SK_REPAIR
{102131}{}{Ремонт}
{102132}{}{Навык починки поврежденных предметов.}
{102133}{}{Ремонт}
# SK_SPEECH
{102141}{}{Убеждение}
{102142}{}{Умение убеждать других и не попадаться на лжи.}
# SK_BARTER
{102151}{}{Торговля}
{102152}{}{Умение заключать выгодные сделки.}
# SK_GAMBLING
{102161}{}{Игра}
{102162}{}{Навык игры (и удача) в кости, карты и тому подобные азартные игры.}
# SK_OUTDOORSMAN
{102171}{}{Гид}
{102172}{}{Совоуцпность знаний о зверях, птицах, растениях и землях.}

# 102300
# TO_SK_FIRST_AID, timeouts
{102301}{}{}
# TO_SK_DOCTOR, timeouts
{102311}{}{Доктор}
# TO_SK_REPAIR, timeouts
{102321}{}{Ремонт}
# TO_SK_SCIENCE, timeouts
{102331}{}{Наука}
# TO_SK_LOCKPICK, timeouts
{102341}{}{Взлом}
# TO_SK_STEAL, timeouts
{102351}{}{Кража}

# 102380
# TO_BATTLE, timeouts
{102381}{}{Боевой}
# TO_TRANSFER, timeouts
#{102391}{}{Переходы}
# TO_REMOVE_FROM_GAME, timeouts
{102401}{}{Выход из игры}
# TO_REPLICATION, timeouts
{102411}{}{Репликация}
# TO_KARMA_VOTING, timeouts
{102421}{}{Голосование}
# TO_SNEAK, timeouts
{102431}{}{Скрытность}
{102441}{}{Свежевательство трупов}
####################################################################################################################################
#
#       Kills (from PROTO.MSG)
#
####################################################################################################################################

#
# Kill Types names
#

# 102600
# BT_MEN..BT_BIG_BAD_BOSS, bodytypes
{102601}{}{Мужчины}
{102602}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей мужского пола.}
{102611}{}{Женщины}
{102612}{}{Здесь указано число убитых вами за время путешествий и приключений человеческих особей женского пола.}
{102811}{}{Полуэльфы}
{102812}{}{Количество полуэльфов, погибших от вашей руки.}
{102821}{}{Полуогры}
{102822}{}{Количество полуогров, погибших от вашей руки.}
{102831}{}{Карлики}
{102832}{}{Количество карликов, погибших от вашей руки.}
{102841}{}{Гномы}
{102842}{}{Количество гномов, погибших от вашей руки.}
{102851}{}{Хоббиты}
{102852}{}{Количество хоббитов, погибших от вашей руки.}
{102861}{}{Полуорки}
{102862}{}{Количество полуорков, погибших от вашей руки.}


####################################################################################################################################
#
#       Perks (with PERK.MSG)
#
####################################################################################################################################

# 103000
{103541}{}{Огнестрельное оружие}
{103542}{}{Новичок:+10 к шансу попадания. Эксперт:+5 к шансу на критический удар. Ветеран: +2 урона к каждой пуле. Мастер:+10 к шансу на критический удар. Великий мастер: + 10 к повреждению}
{103551}{}{Механическое оружие}
{103552}{}{Обращение с механическим оружием}
{103561}{}{Холодное оружием}
{103562}{}{Обращение с холодным оружием}
{103571}{}{Рукопашный бой}
{103572}{}{Рукопашный бой}
{103581}{}{Метание}
{103582}{}{Обращение с метательным оружием}
{103591}{}{------------------}
{103592}{}{--------------------}
{103601}{}{Роковой удар}
{103602}{}{Роковой удар}
{103611}{}{Железный человек}
{103612}{}{Железный человек}
{103621}{}{Снайпер}
{103622}{}{Снайпер}
{103631}{}{Физическая культура}
{103632}{}{+20 к очкам здоровья за каждый разряд умения. }
{103641}{}{Белая некромантия}
{103642}{}{Школа магии:Белая некромантия}
{103651}{}{Чёрная некромантия}
{103652}{}{Школа магии:Чёрная некромантия}
{103661}{}{Магии стихии}
{103662}{}{Школа магии:Стихия}
{103671}{}{Магия природа}
{103672}{}{Школа магии:Природа}
{103681}{}{Магия трансформации}
{103682}{}{Школа магии:Время и пространство}
{103691}{}{Магии разума}
{103692}{}{Школа магии:Разум}
{103701}{}{Магия силы}
{103702}{}{Школа магии:Сила}
{103711}{}{Ремесло:Кузнечное дело}
{103712}{}{Ремесло:Кузнечное дело}
{103721}{}{Ремесло:Оружейное дело}
{103722}{}{Ремесло:Оружейное дело}
{103731}{}{Ремесло:Гербология}
{103732}{}{Ремесло:Гербология}
{103741}{}{Ремесло:Электричество}
{103742}{}{Ремесло:Электричество}
{103751}{}{Ремесло:Терапия}
{103752}{}{Ремесло:Терапия}
{103761}{}{Ремесло:Механика}
{103762}{}{Ремесло:Механика}
{103771}{}{Ремесло:Взрывчатка}
{103772}{}{Ремесло:Взрывчатка}
{103781}{}{Ремесло:Химия}
{103782}{}{Ремесло:Химия}


# 104700

# 104800

# 105000
# DAMAGE_POISONED, damages
{105001}{}{Отравление}
{105002}{}{Ваш персонаж находится под воздействием яда. Это будет отнимать очки жизней, пока вы не вылечитесь или яд не выйдет из организма.}
# DAMAGE_RADIATED, damages
{105011}{}{Облучение}
{105012}{}{Ваш персонаж находится под воздействием поражающего эффекта радиации. Чем сильнее было облучение, тем хуже будет дальнейшая жизнь героя.}
# DAMAGE_EYE, damages
{105021}{}{Ранение в глаз}
{105022}{}{Ваш персонаж был серьезно ранен в один или оба глаза, теперь его Восприятие понизится. Особо уже не присмотришься.}
# DAMAGE_RIGHT_ARM, damages
{105031}{}{Сломана прав. рука}
{105032}{}{Правая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_LEFT_ARM, damages
{105041}{}{Сломана левая рука}
{105042}{}{Левая рука была сильно повреждена и теперь не двигается. Отныне вы не будете применять двуручное оружие. Если вам повредят и другую руку, вы вообще будете воевать непонятно как. Разве только зубами.}
# DAMAGE_RIGHT_LEG, damages
{105051}{}{Сломана прав. нога}
{105052}{}{Ваш персонаж сильно охромел на правую ногу.}
# DAMAGE_LEFT_LEG, damages
{105061}{}{Сломана левая нога}
{105062}{}{Ваш персонаж сильно охромел на левую ногу.}


####################################################################################################################################
#
#       Traits (with TRAIT.MSG)
#
####################################################################################################################################

# 105500
# TRAIT_FAST_METABOLISM
{105501}{}{Быстрый метаболизм}
{105502}{}{Ваш уровень метаболизма вдвое превышает норму. Это означает, что вы будете менее устойчивы к воздействию радиации и ядов, но лечиться будете быстрее.}
# TRAIT_BRUISER
{105511}{}{Крушила}
{105512}{}{Двигаемся помедленнее, но зато повнушительнее. Бьем нечасто, но зато так, чтобы на всю жизнь запомнили! Количество ваших очков Действия уменьшается, но зато Сила увеличивается.}
# TRAIT_SMALL_FRAME
{105521}{}{Xилое тело}
{105522}{}{Вы не так велики, как окружающие, хотя это никогда вам особо не мешало. Вы не в состоянии таскать тяжелые грузы, зато более проворны.}
# TRAIT_ONE_HANDER
{105531}{}{Однорукий}
{105532}{}{Вы хорошо работаете только одной из рук. Благодаря этому вы неплохо владеете обычным оружием, но с двуручным начинаются проблемы.}
# TRAIT_FINESSE
{105541}{}{Точность}
{105542}{}{Все ваши атаки очень точны. Повреждения наносится поменьше, но при этом больше вероятность критического удара.}
# TRAIT_KAMIKAZE
{105551}{}{Камикадзе}
{105552}{}{В бою вы не обращаете внимания на окружающую обстановку и действуете напролом. Это снижает количество ваших очков брони вплоть до минимума, улучшает реакцию в бою.}
# TRAIT_HEAVY_HANDED
{105561}{}{Громила}
{105562}{}{Вы бьете сильно, но не очень точно. Жестокие удары причиняют огромные повреждения врагам, однако почти никогда не оказываются критическими для их состояния.}
# TRAIT_FAST_SHOT
{105571}{}{Быстрый стрелок}
{105572}{}{У вас нет времени для нормального прицеливания, поэтому стреляете наугад, лишь бы побыстрее. Для применения оружия вам требуется на одно очко действий меньше.}
# TRAIT_BLOODY_MESS
{105581}{}{Маньяк}
{105582}{}{По странной случайности, люди вокруг вас умирают страшной, мучительной смертью. Для них вы находите худший вариант кончины.}
# TRAIT_JINXED
{105591}{}{Дурной глаз}
{105592}{}{Xорошая сторона дела заключается в том, что ваши враги постоянно ошибаются. Плохо то, что вы ошибаетесь не меньше их!}
# TRAIT_GOOD_NATURED
{105601}{}{Добродушие}
{105602}{}{В детстве вы занимались тихими, размеренными занятиями и не делали зарядку. Ваши боевые умения меньше, чем у других, но зато Первая Помощь, Доктор, Беседа и Торговля заметно лучше.}
# TRAIT_CHEM_RELIANT
{105611}{}{Неуст. к химии}
{105612}{}{Вы легче попадаете в зависимость от химикалий. Вероятность привыкания к разным веществам вдвое больше, чем норма, правда, вы проще переносите их эффект.}
# TRAIT_CHEM_RESISTANT
{105621}{}{Уст. к химии}
{105622}{}{Xимикалии приносят вам только половину нормального эффекта, но вероятность привыкания также снижена на 50% от нормы.}
# TRAIT_SEX_APPEAL
{105631}{}{Сексуальность}
{105632}{}{Вы умеете "правильно" обходиться с людьми другого пола. Однако ваше стремление совращать всех попало, может раздражать окружающих.}
# TRAIT_SKILLED
{105641}{}{Умелец}
{105642}{}{Так как вы неустанно работали над собой и постоянно улучшали свои возможности, то начнете игру с улучшенными параметрами. С другой стороны, вы получаете меньше доп. умений - одно за каждые 4 уровня.}
# TRAIT_NIGHT_PERSON
{105651}{}{Ночная персона}
{105652}{}{Совы вроде вас просыпаются обычно тогда, когда солнце заходит за горизонт. Параметры Интеллекта и Восприятия увеличиваются на 1 в ночное время суток (от 18:01 до 06:00), и уменьшаются тоже на один утром (от 06:01 до 18:00).}
# TRAIT_GIFTED
{105661}{}{Талант}
{105662}{}{Вы очень одарены различными способностями и превосходите обычный уровень. Все ваши параметры больше на единицу, но вы теряете 10% для умений и получаете на 5 очков меньше за уровень.}


# Reputation groups
#105700

####################################################################################################################################
#
#       3d attributes
#
####################################################################################################################################

# Body types
{150100}{}{Человек}
{150101}{}{Гном}
{150102}{}{Эльф}
{150103}{}{Полуэльф}
{150104}{}{Карлик}
{150105}{}{Полурослик}
{150106}{}{Полуорк}
{150107}{}{Полуогр}
{150108}{}{Орк}

{155070}{}{Раса}

#race description
{155080}{}{Человек}
{155081}{}{Человек не отличается особыми способностями. Люди - самая распространенная раса. Они могут прекрасно общаться со всеми остальными расами и скрещиваться с ними, откуда берутся полуэльфы, полу-огры и полу-орки. У людей нет врожденных спсобностей к магии, но эта короткоживущая раса отлично приспосабливается к окружающей среде и может добиться неплохих успехов.}}

{155090}{}{Гном}
{155091}{}{Вы получаете +1 к Силе, +1 к Фигуре, +15% к технике, и +2 ко всем Техническим умениям. Взамен вы получаете -1 к Обаянию и Ловкости, заклинания стоят в 2 раза больше. Гномы низкорослы, бородаты, мускулисты и очень любят пиво. Гномы не любят эльфов еще со времен войны за сильмариллы, но сдружились с людьми.}

{155100}{}{Эльф}
{155101}{}{Вы получаете +1 к Ловкости, Воле, и Красоте, +15% к Магии, но -2 к Фигуре и -1 к Силе, а также -2 ко всей технике. Эльфы - золотоволосая раса, красоте которой завидуют все расы Арканума. Из-за давней распри, начавшейся еще со времен войны за Сильмариллы эльфы недолюбливают гномов.}

{155110}{}{Полуэльф}
{155111}{}{Персонаж +1 к Ловкости и Красоте, +5% к магии, но теряет -1 к Фигуре и -1 ко всем техническим наавыкам. По телосложению и внешности полуэльфы напоминают своих человеческих родителей, но некоторые полуэльфы похожи по телосложению и на эльфийских предков. Полуэльфы не склонны к конфликтам и к ним одинаково относятся все расы.}

{155120}{}{Карлик}
{155121}{}{Вы получаете +2 к воле, +2 к Торговле, и +10 к реакции, но зато -2 к фигуре. Карлики небольшого роста, с большими носами, худы. Они могут выжить где угодно и отлично чувствуют себя как в городе так и в лесу. }

{155130}{}{Полурослик}
{155131}{}{Вы получаете +2 к Ловкости, +2 к Маскировке, +1 к Уклончивости и 5% шанс нанести критический удар, но зато  -3 к Силе. Хоббиты - невысокий народ, они даже меньше по росту, чем карлики. Очень любят хорошо покушать. Не носят обуви, потому что у них твердые ступни, а ноги покрыты шерстью. Хоббиты - мирные сельские жители, не имеющие никаких дел ни с магией, ни с техникой. Другие расы считают их ленивыми, но все любят.}

{155140}{}{Полуорк}
{155141}{}{Вы получаете +1 к фигуре, +1 к Силе, +2 к Рукопашной и Увертливости и 10% устойчивость к ядам, но -2 к красоте и -2 к обаянию. Саруман создал полуорков скрестив похищенных человеческих женщин с верными ему орками. Получившаяся раса отличалась преданностью, не свойственной оркам и кровожадностью, не свойственной людям. Эти дети всемогущего Эру недолюбливают людей и люди не остаются в долгу.}

{155150}{}{Полуогр}
{155151}{}{Вы получаете +4 к Силе и 10% к Сопротивляемости вреду , но -1 к Красоте, -2 к Маскировке, и -4 к Интеллекту. Полуогры - результат скрещивания огров и людей, крайне редкое сочетание. Полуогры очень велики, но достаточно добродушны. Могут носить больший груз и больше доспехов. Благодаря большой силе редко кто пытается их задирать.}

{155160}{}{Орк}
{155161}{}{Вы получаете +4 к Силе и 10% к Сопротивляемости вреду , но -1 к Красоте, -2 к Маскировке, и -4 к Интеллекту. Полуогры - результат скрещивания огров и людей, крайне редкое сочетание. Полуогры очень велики, но достаточно добродушны. Могут носить больший груз и больше доспехов. Благодаря большой силе редко кто пытается их задирать.}

{156150}{}{Биография}

#no descr
{156160}{}{Нет данных}
{156161}{}{С этим персонажем никогда никогда ничего не происходило.}

#snake eater
{156170}{}{Воспитанник змей}
{156171}{}{Вы получаете 20% устойчивости к ядам, но красота ухудшается на -1 из-за шрамов от укусов на руках и ногах.}

#elf parents
{156180}{}{Воспитанник Эльфов}
{156181}{}{Вы начинаете с замечательной эльфийской кольчугой, но не разбираетесь в технике}

#monk parents
{156190}{}{Питомец монахов}
{156191}{}{У монахов есть как плюсы так и минусы. У вас улучшается наблюдательность (+1), но все деньги в начале вы раздали нищим.}

#hero child
{156200}{}{Дитя Героя}
{156201}{}{Вы начинаете с отцовским мечом +1 + вас все знают как дитя Героя. Любой злое действие будет наказано на месте.}

#money child
{156210}{}{Наследник}
{156211}{}{Вы потеряли родителей в детстве и получили кучу монет. В реультате у вас ухудшилась воля (-1). Большая часть бабок оже прокучена, но их все равно в 2 раза больше чем у других.}

#elf citytard
{156220}{}{Фатоватый Эльф}
{156221}{}{Вы выросли в людском городе и эльфийскую ловкость, но зато стали отличным оратором.}

#dwarf no clan
{156230}{}{Гном без Клана}
{156231}{}{Ваши родители не принадлежали ни к одному из кланов, и никогда не говорили вам, почему. Вы не получаете гномского улучшения к техническим умениям, но начинаете с прекрасным боевым молотом гномов.}

#gnome outlaw
{156240}{}{Лишенный Гражданских Прав Карлик}
{156241}{}{Вы не являетесь частью карличьей буржуазии и росли, занимаясь поденной работой. Вы получаете уменьшение Торговли, но улучшение к Силе (+1).}

#hobbit orphan
{156250}{}{Сирота Полурослик}
{156251}{}{Вы были ребенком покинуты в большом городе, жили воровством и никогда не получали никакого образования. Вы получаете улучшение навыка Воровства, но теряете пункты Интеллекта (-1).}

#curious person
{156260}{}{Особая Личность}
{156261}{}{У вас врожденное повреждение мозга. Вы теряете Интеллект (-2), но получаете больше похвал, когда делаете добрые дела (в результате чего люди начинают лучше реагировать на вас).}

#knifetrower
{156270}{}{Профессиональный Метатель Ножей}
{156271}{}{Вы работали в цирке метателем ножей, пока не потеряли глаз при несчастном случае. К сожалению, вы теряете пункт Восприятия (-1), но получаете дополнительное улучшение к навыку Метания.}

{156280}{}{Подмастерье у Лавочника}
{156281}{}{Вы все детство провели в лавке, и получаете исключительное улучшение Торговли, но страдаете от уменьшения Ловкости (-1).}

{156290}{}{Посланы в Школу Очарования}
{156291}{}{Вы не получили обычного образования, потому что вас отправили в школу очарования. Вы получаете улучшение Внешности (+1) и Обаяния (+2),но теряете пункты в Интеллекте (-1) и Силе (-2).}

{156300}{}{Рождены под Знаком}
{156301}{}{Вы рождены во время какого-то астрономического события. В результате вы испытали мало ударов судьбы и серьезных потерь, но когда вам они доставались, это оказывало на вас ошеломляющее действие.}

{156310}{}{Исключительная личность}
{156311}{}{Вы являетесь исключительной личностью. Люди бурно реагируют на ваше присутствие, и их чувства перерастают либо в любовь, либо в ненависть.}

{156320}{}{Беглец с завода}
{156321}{}{До недавнего побега вы были рабом на заводе. У вас мало денег, но вы получаете улучшение Силы (+1).}

{156330}{}{Свободный телохранитель}
{156331}{}{Ваш хозяин-карлик недавно умер, и по его завещанию вы были освобождены и отпущены с небольшим денежным вознаграждением. Однако, вы не очень-то блещете умом и получаете ухудшение Интеллекта (-1).}

{156340}{}{Книжный червь}
{156341}{}{Большую часть жизни вы провели за чтением. Вы получаете улучшение Интеллекта (+1). К сожалению, вы заработали при этом близорукость и теряете в Восприятии (-1).}

{156350}{}{Задира}
{156351}{}{Вы были задирой, большим и неразговорчивым. Вымогательство и запугивание улучшили вашу Силу (+1), но поскольку вы всегда заставляли людей делать за вас домашнее задание, имеет место некоторый недостаток Интеллекта (-1).}

{156360}{}{Дикий Полуогр}
{156361}{}{Вы родились у матери огра и жили среди огров до самого последнего времени. Как и ваши более цивилизованные братья вы получаете улучшение Воли (+1), но страдаете от ухудшения Обаяния (-1).}

{156370}{}{Полуогр Редкий По Рождению}
{156371}{}{Вы родились от человеческой матери, которая каким-то образом пережила ваше рождение. Вы выросли в городе и получаете значительное улучшение Интеллекта (+2). Однако, городская жизнь убавила вашу свирепость, и вы теряете в Силе (-1) и Сложении (-1).}

{156380}{}{Подавлены Внешностью Орка}
{156381}{}{На самом деле вы не очень похожи на орка, но исключительно угрюмы. Вы получаете улучшение Внешности (+2), но страдаете от уменьшения Обаяния (-2).}

{156390}{}{Эльфийская Кровь}
{156391}{}{Прабабушка вашего отца была эльфом. Вы получаете улучшение Магических Способностей (5%), но страдаете от легкого ухудшения всех технических навыков.}

{156400}{}{Гиперактивность}
{156401}{}{Вы постоянно заняты. Ваша Скорость выше нормальной (+1), но большинство людей считают, что вы их утомляете, и ваше Обаяние ухудшается (-1).}

{156410}{}{Обучение в Армии}
{156411}{}{В юности вы прошли обучение в армии, но были демобилизованы из-за плоскостопия. Вы получаете улучшение Силы (+1), а также незначительное улучшение навыков Рукопашной и Стрельбы из лука, однако ваша Ловкость ухудшается (-1).}

{156420}{}{Толстокожий}
{156421}{}{Вы родились с толстой, грубой кожей. Хотя вы лучше обычных людей сопротивляетесь урону (10%), к несчастью получаете ухудшение Внешности (-1).}

{156430}{}{Детство под Сверхопекой}
{156431}{}{Пока вы были ребенком, вас холили и лелеяли. В результате этой суперопеки вы получаете серьезнейшее ухудшение Силы (-6), но, из-за повышенной чувствительности, получаете улучшения Интеллекта (+2), Воли (+2), и Восприятия (+1).}

{156440}{}{Потомок Троллей}
{156441}{}{Боги смеялись над вами, когда вы родились. Вы выглядите, как тролль, и ведете себя, как тролль, и следовательно получаете значительное ухудшение Внешности (-4) и Обаяния (-4). Поскольку все вас считают отродьем монстра, или даже хуже, вам часто приходится отбиваться от охотников и священников, так что вы получаете улучшение Силы (+2), Сложения (+2), и Ловкости (+1).}

{156450}{}{Убежали с Цирком}
{156451}{}{Убежав из дому с цирковой труппой, вы получаете значительное улучшение физической Силы (+6), но испытываете недостаток Интеллекта (-2), Воли (-3), и Восприятия (-1), поскольку недоучились в школе.}

{156460}{}{Выращены в Копях}
{156461}{}{Будучи ветераном местных драк, вы получаете улучшение Силы (+2), Ловкости (+2), а также улучшение всех Боевых Навыков. Однако, постоянные сражения не прошли бесследно. Из-за травмы головы у вас очень плохо с Интеллектом (-6). В результате, вы не очень-то хорошо умеете обращаться с деньгами. За всю свою жизнь вы едва-едва накопили 100 монет.}

{156470}{}{Одичавший Ребенок}
{156471}{}{Еще младенцем ваши родители оставили вас в чаще леса. Вы выросли в стае волков, и получаете значительное улучшение Ловкости (+3) и легкое улучшение Воровских Навыков, таких, как Скрытность и Воровство. Но неумение вести себя, и незнание законов общества приводит к значительному снижению Интеллекта (-6) а также легкому ухудшению Социальных Навыков, таких как Красноречие и Торговля. Вы начинаете с половиной обычной стартовой суммы денег.}

{156480}{}{Больной}
{156481}{}{Мать Природа может быть суровой Госпожой. Вы родились с ослабленной иммунной системой, и получаете ухудшение Силы (-2), Сложения (-4), и Ловкости (-1). Но не все так плохо. Пока вас терзала лихорадка, вы не выпускали из рук книгу, и это наградило вас неестественно большим Интеллектом (+6).}

{156490}{}{Прокляты Уродством}
{156491}{}{Вы уродливы. Лучше слова не подберешь, хотя иногда вам кажется, что слово омерзительно тоже подошло бы. Дети в страхе разбегаются, когда видят вас, и даже самые добрые люди не в силах подолгу выносить ваше присутствие. В результате вы получаете серьезнейшее ухудшение Внешности (-6), но, поскольку вам постоянно приходится защищаться от нападений, вы получаете улучшение Силы (+2), Ловкости (+2) и легкое улучшение всех ваших Боевых Навыков.}

{156500}{}{Дамский Угодник}
{156501}{}{Женщины всегда стараются подойти к вам поближе. Вы необычайно красивы, и получаете улучшение Внешности (+6). К несчастью, прихорашиваясь и пудрясь вы потеряли нечто гораздо более ценное... вы теряете очки в Сложении (-2), Силе (-2) и Ловкости (-2).}

{156510}{}{Дебютант}
{156511}{}{Ваша семья - одна из наиболее влиятельных во всем Аркануме. Будучи дебютанткой, вы получаете улучшение Внешности (+3) и Обаяния (+3). разумеется, благодаря легкой жизни, вы несколько ослабли разумом и телом. Вы получаете ухудшение Силы (-1), Ловкости (-1), и всех ваших Боевых Навыков.}

{156520}{}{Выращены Орками}
{156521}{}{Вы были беглым сиротой, бездомным и голодающим, однако семья орков приняла вас к себе и вырастила. Суровый образ жизни орков дал вам улучшение Силы (+2) и Восприятия (+2), кроме того, вы получаете легкое улучшение всех Боевых Навыков. К несчастью, ваша приемная семья наложила свой отпечаток на развитие вашей личности, так часто вы получаете значительное ухудшение Обаяния (-6).}

{156530}{}{Протеже Шарлатана}
{156531}{}{Бродячий торговец убедил вас стать своим подмастерьем, и вы покончили с жизнью в военной академии, куда были записаны. Вы получаете существенное улучшение Обаяния (+6), но теряете в физической Силе (-2), Сложении (-2), а также страдаете от незначительного ухудшения всех ваших Боевых Навыков.}

{156540}{}{Преподаватель}
{156541}{}{Вы по натуре учитель. Как только вы начинаете чему-то учиться, вы можете показать своим последователям предыдущий шаг в обучении. Так что, будучи Экспертом, вы можете выучить своих последователей на Подмастерье, если у них есть на это право. Однако, поскольку вам приходится тратить много времени на каждого последователя, вы не можете иметь обычное количество последователей (-1 от максимума).}

{156550}{}{Супер Модель}
{156551}{}{Вы исключительно эффектная женщина, так что вас баловали и нежили всю вашу жизнь. Вы получаете сильнейшее улучшение Внешности (+6) ценой Силы (-2) и Интеллекта (-4).}

{156560}{}{Сбежавший Лунатик}
{156561}{}{Вы сбежали из сумасшедшего дома и прокрались на борт Дирижабля Зефир. У вас исключительная сопротивляемость урону (+25% к сопротивляемости огню, электричеству и яду) но у вас нет денег, вы украли кое-какую дешевую одежду, и большинство людей боятся и отталкивают вас (-25 реакции).}

{156570}{}{Свихнувшийся Ученый}
{156571}{}{В юные годы вы были помещены в лечебницу и считались умственно неполноценным. Через несколько лет в лечебнице кончились деньги и вас выбросили на улицу, не дав вам ничего кроме одежды, которая на вас была. Вы великолепно разбираетесь в математике и числах, но с трудом можете говорить. Вы получаете значительное улучшение Интеллекта (+6) и дополнительное улучшения навыка Игры. Однако, проведенные взаперти годы заставляют вас страдать физически и эмоционально. вы говорите так, словно у вас совсем плохо с интеллектом, страдаете от ухудшения Силы (-1), Сложения (-1), Ловкости (-2) и Воли (-2).}

{156580}{}{Сорванец}
{156581}{}{Будучи маленькой девочкой вы всегда играли с мальчишками. Став женщиной, вы в состоянии противопоставить себя любому мужчине, и вам не нравятся обычная роль женщины в обществе. таким образом вы получаете улучшение Силы (+1) при ухудшении Сложения (-1).}

{156590}{}{Варвар}
{156591}{}{Вы выросли в диком варварском племени в далекой стране. Никто не знает, как и почему вы стали пассажиром Дирижабля Зефир, но, благодаря вашему устрашающему поведению, никто и не пытается выяснить это. Вы получаете улучшение Силы (+2) и Сложения (+1), а также незначительное улучшения навыка Рукопашной, но страдаете от ухудшения Интеллекта (-1) и Обаяния (-2), а также Торговли. У вас есть варварский доспех, но меньше денег, чем у остальных персонажей.}

{156600}{}{Дитя Теории Ницше}
{156601}{}{Ницше когда-то сказал "То, что не убивает меня, делает меня сильнее", и это явно относится к вам. Всю вашу жизнь вы ошибались, но впоследствии это всегда оказывалось к лучшему. Другими словами, вы допускаете критические промахи чаще обычного но получаете бонус в 10% очков опыта.}

{156610}{}{Последователь Темных Эльфов}
{156611}{}{Вы верите в философию темных эльфов, согласно которой технологии должны быть уничтожены любой ценой. Эта вера укрепила вашу Волю (+2), но из-за недавнего расцвета технологий вы потеряли в Обаянии (-2).}

{156620}{}{Продали Свою Душу}
{156621}{}{Вы заключили соглашение с демоном. В обмен на магическую силу, вы должны были посвятить свою жизнь злу. Вы получаете 20% к Магическим Способностям, но страдаете из-за реакции других -20 и стиля характера -20 (и ваш стиль характера НИКОГДА не улучшится).}

{156630}{}{Дневной Маг}
{156631}{}{Вы родились с магическими способностями, зависящими от солнца. Днем (с 6 утра до 6 вечера), вы получаете 20% улучшения к вашим Магическим Способностям, а ночью страдаете от 20% ухудшения Магических способностей.}

{156640}{}{Ночной Маг}
{156641}{}{Вы родились с магическими способностями, зависящими от ночи. Ночью (с 6 вечера до 6 утра), вы получаете 20% улучшения к вашим Магическим Способностям, а днем страдаете от 20% ухудшения Магических способностей.}

{156650}{}{Небесный Маг}
{156651}{}{Вы родились с магическими способностями, зависящими от открытого неба. На улице, когда небо ясно видно, вы получаете 20% улучшения к вашим Магическим Способностям. Однако под землей, в помещении и даже в густом лесу, вы страдаете от 20% ухудшения Магических способностей.}

{156660}{}{Природный маг}
{156661}{}{Вы родились с магическими способностями, зависящими от природы. Оказываясь на лоне природы, вы получаете 20% улучшения к вашим Магическим Способностям. А на поверхности. созданной руками человека, вы страдаете от 20% ухудшения Магических способностей..}

{156670}{}{Агорафобия}
{156671}{}{У вас боязнь открытых пространств. ребенком, вы редко выходили на улицу, и проводили время за чтением и учебой, набирая улучшение Интеллекта (+2). Вы хорошо себя чувствуете в помещении и даже в густом лесу, но попадая на открытое пространство, вы впадаете в панику, теряете улучшение Интеллекта и получаете ухудшение Ловкости (-2), Интеллекта (-2) и Воли (-2), но при этом увеличивается ваша Сила (+2) от страха.}

{156680}{}{Гидрофобия}
{156681}{}{Вы смертельно боитесь воды, боитесь утонуть. Ребенком, вы постоянно пытались избежать соприкосновения с водой, даже с мелкими лужицами, и получаете улучшение к Восприятию. Оказавшись в воде, вы впадаете в панику, и получаете ухудшение Ловкости (-2), Интеллекта (-2) и Воли (-2), но при этом увеличивается ваша Сила (+2) от страха.}

{156690}{}{Боязнь Темноты}
{156691}{}{Вы не выносите темноты. Вы постоянно всего боитесь, вглядываетесь в темные углы и тени, боясь что-то там увидеть. Хотя при этом улучшилось ваше Восприятие (+2), вы впадаете в панику, оказавшись в темноте, что ведет к ухудшению Ловкости (-2), Интеллекта (-2) и Воли (-2), но при этом увеличивается ваша Сила (+2) от страха.}

{156700}{}{Аллергия на Магию}
{156701}{}{У вас ужасная аллергия на магические предметы, одно прикосновение к ним причиняет вам страшную боль. Таким образом, вам сызмальства пришлось заниматься Технологией, и вы прекрасно овладели ею. Вы получаете улучшение +10% к Технологическим Способностям, но не можете обладать НИКАКИМИ магическими вещами.}

{156710}{}{Поджигател}
{156711}{}{вам нравится огонь. Нет, вы ЛЮБИТЕ огонь! Огонь! Огонь! ОГОНЬ! Вас всегда дразнили как задохлика, и вы получаете ухудшение Силы (-1) и Сложения (-1), но вы показали им! Вы изучали взрывчатые вещества, заработав +20 Квалификации, вы сожгли их дома! Сожгли дотла! Ха-ха! Затем вы убежали из дома и пробрались на борт дирижабля Зефир. который казался вам легко воспламеняемой и прекрасной целью. И вы бы наверняка превратили его в факел. если бы он не был сбит раньше.}

{156720}{}{Бандит}
{156721}{}{Вы ужасный бандит. Благодаря своему стилю жизни вы заработали улучшение к навыку Владения Огнестрельным Оружием, и ухудшите Обаяние (-1). Вы постоянно находитесь в конфликте с законом и достигли Дирижабля Зефир всего на шаг впереди властей. У вас есть ружье и боеприпасы, но совсем нет денег.}

{156730}{}{Технофобия}
{156731}{}{Вы выросли на ферме по выращиванию картофеля, в тихой заводи вдали от больших городов. Вы много работали, заработав улучшение Силы (+1) и Сложения (+1), но никогда не были знакомы ни с какими технологиями. Не удивительно, что вы боитесь технологических предметов и не в силах заставить себя даже взять их в руки.}

{156740}{}{Только Ребенок}
{156741}{}{Вы были единственным ребенком все позволяющих родителей, и всегда предпочитали сами выбирать свою дорогу. Став взрослым, вы ожидаете от всех полного повиновения, заработав улучшение Воли (+6), но ваш темперамент оставляет желать много лучшего, и это отражается на ухудшении вашего Обаяния (-4) а также навыков Красноречия и Торговли.}

{156750}{}{Чудовище Франкенштейна}
{156751}{}{Вы были созданы безумным ученым из различных частей тела, которые он насобирал на кладбищах, но каким-то образом вы бежали из его лаборатории. Вы очень хорошо сконструированы, и получаете улучшение Силы (+4), Сложения (+4), Сопротивляемости Электричеству (+30%) и Сопротивляемости Ядам (+20%), но почти не обладаете Ловкостью (-6), но при этом у вас повреждена связь мозга и гортани (у вас сокращены опции диалога) и повышенная чувствительность к огню, Сопротивляемость Огню (-20%). Кроме того, вы начинаете совершенно без денег.}

{156760}{}{Невеста Франкенштейна}
{156761}{}{Безумный ученый реанимировал вас, чтобы сделать невестой другого своего создания, но каким-то образом вам удалось бежать до свадьбы. Вы очень хорошо сконструированы, и получаете улучшение Внешности (+4), Сложения (+4), Сопротивляемости Электричеству (+20%) и Сопротивляемости Ядам (+10%), но почти не обладаете Ловкостью (-4), но при этом у вас повреждена связь мозга и гортани (у вас сокращены опции диалога) и повышенная чувствительность к огню, Сопротивляемость Огню (-10%). Кроме того, вы начинаете совершенно без денег.}

{156770}{}{Безумный Доктор}
{156771}{}{Вы провели множество непроверенных и опасных медицинских экспериментов над собой и страдаете от последствий собственного безрассудства. Вы получаете улучшение Интеллекта (+2), Восприятия (+2), Сопротивляемости Ядам (+20%) и Сопротивляемости Электричеству (+20%), а также улучшение навыка Лечения (+1), но страдаете от ухудшения Внешности (-1), Обаяния (-1), Ловкости (-2) и Конституции (-3).}

{156780}{}{Чудесная операция}
{156781}{}{Родившись в богатой семье, вы в раннем детстве потеряли зрение. Оказалось, что вы заболели тяжелой болезнью. Будучи слепым, вы рано предпочли деятельность, доступную в закрытых помещениях, а также ту, что подходит только для богатых членов общества. Вы получаете улучшение Интеллекта (+3) и Обаяния (+3). Ваши осязание, слух и обоняние сильно развились, компенсируя слепоту, что дало вам улучшение Восприятия (+5). Однако, вы пострадали физически, что привело к ухудшению Силы (-3), Ловкости (-3) и Сложения (-5). Вы повзрослели, и ваши родители оплатили услуги известного врача, который каким-то чудом вернул вам зрение. Операция стоила вашей семье состояния, так что вы отправляетесь заработать собственное.}

{156790}{}{Видение в Темноте}
{156791}{}{Ваши глаза всегда были чувствительны к свету. При дневном свете вы почти слепы, но прекрасно видите в темноте. Таким образом, все ухудшения навыков, связанные со светом, для вас перевернуты.}












####################################################################################################################################
#
#       Misc2 values names (100000 + pid*10 + number of val)
#
####################################################################################################################################


# музыка в городах 
# pid*10+1000000    играть всё время одну дневную мелодию? true/false
# pid*10+1000000+1  название музыки без _day _night и .wav


# Blackberry
{1000020}{}{false}
{1000021}{}{city}

# Bridd
{1000030}{}{false}
{1000031}{}{city}

# Tedlook
{1000090}{}{false}
{1000091}{}{city}

{1001000}{}{Заряд}
{1001001}{}{}
{1001002}{}{}


####################################################################################################################################
#
#       Intellect words
#
####################################################################################################################################

{1999000000}{}{
я  моя
ты  твоя
вы  ваша
мы  наша
меня  мою
мне  моей
тебя  твою
сказал  сказать
скажу  сказать
скажи  сказать
убил  убивай
убили  убивай
убью  убивай
убей  убивай
украл  украсть
укради  украсть
своровал  украсть
своруй  украсть
воровать  красть
хочу  хотеть
хотел  хотеть
положил  положить
положи  положить
дал  давать
дай  давать
верни  вернуть
вернул  вернуть
верну  вернуть
отдай  отдать
отдал  отдать
отдам  отдать
могу  мочь
говорить  гварить
говорю  гварить
понимаю  понимать
они  их
думаю  думать
думайте  думать
думаем  думать
думай  думать
бежать  бечь
бегу  бечь
беги  бечь
бегите  бечь
бежим  бечь
побежал  бечь
побежали  бечь
идти  ити
идти  ходить
хожу  ходить
интеллект  ум
взял  взять
взяли  взять
возьми  взять
возьмите  взять
возьму  взять
возьмем  взять
злодей  плохой
злодей  злой
убийца  плохой
убийца  злой
бандит  плохой
бандит  злой
рейдер  плохой
рейдер  злой
злодеи  плохие
злодеи  злые
убийцы  плохие
убийцы  злые
бандиты  плохие
бандиты  злые
рейдеры  плохие
рейдеры  злые
брамин  му-му
брамины  му-му
коровы  му-му
корова  му-му
караван  корован
караваны  корованны
дерьмо  какашки
черт  шайтан
иду  ходить
иди  ходить
пошел  ходить
пошли  ходить
пойду  ходить
пойди  ходить
пришел  приходить
шел  ходил
присоединяйся  твоя ходить за моей
присоединись  твоя ходить за моей
присоединяйтесь  ваша ходить за нашей
присоединитесь  ваша ходить за нашей
присоединился  твоя ходить за моей
присоединяемся  наша ходить за вашей
присоединились  наша с вашей ходить
присоединяюсь  моя ходить за твоей
присоединюсь  моя ходить за твоей
научи  научай
научите  научайте
моего  мой
моих  мои
моего  мое
мою  мой
враг  плохой
враг  злой
враги  злые
друг  хороший
друг  приятный
друга  хорошево
друзья  други
друзья  хорошие
нормальный  хороший
нормальные  хорошие
привет  моя приветствует
здравствуй  моя здаровается
здравствуйте  моя здаровается
машина  би-бип
хамер  би-бип
джип  би-бип
оружие  пиу-пиу
you  u
are  r
i  me
want  wanting
why  y
could  was can
did  doed
into  in
had  haved
joing  go wiz mi
the
am
a
an
}

{1999000001}{}{
а  а
а  я
б  б
б  п
в  в
в  ф
г  в
г  г
г  х
г  к
д  д
д  т
е  е
е  э
е  ё
е  й
е  йэ
е  о
ё  ё
ё  е
ё  о
ё  йо
ж  ж
ж  з
з  з
з  с
з  ж
и  и
и  е
и  ы
й  й
й  е
й  и
к  к
к  г
л  л
л  р
м  м
н  н
о  а
о  ё
п  п
п  б
р  р
р  л
с  с
с  з
т  т
т  д
у  у
у  о
у  ю
ф  ф
ф  в
х  х
х  г
ц  ц
ц  тс
ч  ч
ш  ш
щ  щ
щ  шч
ъ
ы  ы
ы  и
ь
э  э
э  е
э  йе
ю  ю
ю  йу
ю  у
я  я
я  йа
я  а
a  a
b  b
c  c
c  k
d  d
e  e
f  f
f  v
f  w
g  g
g  j
h  h
i  i
j  j
j  g
k  k
k  q
l  l
m  m
n  n
o  o
p  p
q  q
r  r
s  s
t  t
u  u
v  v
v  f
v  w
w  w
w  v
w  f
x  x
x  ks
y  y
z  z
th  z
ing  in
}

####################################################################################################################################
#
#       Help
#
####################################################################################################################################

# F7 - Включить/выключить подсветку имен нпц.
# F9 - Включить/выключить трассировку траектории выстрела.

{2000000000}{}{
Горячие клавиши в игре:

F1 - Включить/выключить помощь.
F2 - Сохранить сообщения в файл.
F3 - Сохранить скриншот.
F4 - Вкл./Выкл. отображение панели ввода текста.
F5 - Вкл./Выкл. расширение окна сообщений.
F6 - Включить/выключить подсветку имен игроков.
F8 - Включить/выключить скроллинг карты мышкой (помогает в оконном режиме).
F12 - Сворачивание клиента.
Указатели - скроллинг карты.
Esc - меню.
Pause/Break - пунтосвитчер в командной строке.
<,> - Вращаться против часовой или по часовой стрелке.
Home - центрирование на персонаже (на карте и на глобале).
A - Атака.
G - Подобрать итем под ногами.
C - Персонаж.
I - Инвентарь.
P - Пипбой.
F - Фиксбой.
B - Переключение активных слотов.
M - Переключение меню мыши.
N - Переключение режима итема.
S - Панель навыков.
Z - Масштабирование карты.
1-8 - Выбор навыка.
? - Текущее игровое время.
+,- - Регулирование яркости.
Ctrl + +,- - Регулирование громкости звуков.
Shift + +,- - Регулирование громкости музыки.
Alt + +,- - Регулирование Sleep.

Команды для общения:
первый символ . или / потом:
к К s S - кричать,
ш Ш w W - шептать,
э Э e E - эмоция,
р Р r R - рация.
После пробел можно не ставить, а если и поставите, то он игнорируется.
Введите сообщение и нажмите Enter.

Так же возможна отправка сообщений с помощью:
Ctrl + Enter - крик,
Alt + Enter - шепот,
Shift + Enter - рация.
}

####################################################################################################################################
#
#       Credits
#
####################################################################################################################################

# # == "|0xff8c8c84 "
# @ == "|0xff706050 "
# normal == "|0xff907824 "

{2000001000}{}{35} # Speed
{2000001010}{}{|4294967295
Under construction












Under construction









Under construction







Under construction









Under construction








Under construction















































Yes, is still Under construction
}
# Shift + Credits
{2000001020}{}{
Hello world!
}


