{2900}{}{Патроны}
{2901}{}{Незаменимы для каждого ценителя огнестрельного оружия!}
{3100}{}{0,44 Магнум п/об}
{3101}{}{Обойма патронов, калибр 0,44 Магнум, полуоболочечные.}
{3200}{}{Топливо}
{3201}{}{Высокооктановое топливо для любителей пиротехнических забав.}
{3900}{}{Батарея}
{3901}{}{Наиболее распространённый элемент питания для всего электрического барахла}
{4100}{}{Деньги}
{4101}{}{Деньги.}
{20000}{}{Абсент}
{20100}{}{Клубный Кларет}
{20200}{}{Джин}
{20300}{}{Мадера}
{20400}{}{Шампанское}
{20500}{}{Сидр}
{20600}{}{Виски}
{20700}{}{Коньяк}
{20800}{}{Бренди}
{20900}{}{Сироп от кашля Бирмана}
{21000}{}{Пинта светлого}
{21100}{}{Пинта темного}
{21200}{}{Чашка чая "Эрл грей"}
{21300}{}{Херес}
{21400}{}{Портвейн}
{21500}{}{Горькая настойка Уистлера}
{21600}{}{Настойка Вормана}
{21700}{}{Арманьяк}
{82000}{}{DONT USE: Невидимый блокиратор}
{100000}{}{!Unarmed!   punch}
{100100}{}{!Unarmed!   strong punch}
{100200}{}{!Unarmed!   hammer punch}
{100300}{}{!Unarmed!   haymaker}
{101000}{}{!Unarmed!   jab}
{101100}{}{!Unarmed!   palm strike}
{101200}{}{!Unarmed!   piercing strike}
{102000}{}{!Unarmed!   kick}
{102100}{}{!Unarmed!   strong kick}
{102200}{}{!Unarmed!   snap kick}
{102300}{}{!Unarmed!   power kick}
{103000}{}{!Unarmed!   hip kick}
{103100}{}{!Unarmed!   hook kick}
{103200}{}{!Unarmed!   piercing kick}
{103300}{}{Точный Револьвер}
{103301}{}{Достиженяи в металлургии помогли оружейному делу в последние годы, этот сбалансированный и элегнатный пистолет появился как первый выбор ученых и простых человек по всему миру. С улучшенным пусковым механизмом и камерой, это оружие показало себя постоянно отлично работающим ис лучшей магической сопротивляемостью.}
{103400}{}{Одноручный меч}
{103401}{}{}
{103500}{}{Топор дровосека}
{103501}{}{Да, вы не ослышались. Это топор дровосека.}
{103600}{}{Снайперский арбалет}
{103601}{}{Отличная пробивная сила арбалета помноженная на хрустальную линзу горного хермандита.Убийственная точность!}
{103700}{}{Обычный арбалет}
{103701}{}{Обычный 4-х зарядный арбалет. Хороший выбор как для охотника, так и для убийцы}
{103800}{}{Кремниевый пистолет}
{103801}{}{Обычный однозарядный кремниевый пистолет. Поройся в мусорном ящике и собери себе такой!}
{103900}{}{Шпага дуэльная}
{103901}{}{Обычная шпага для обычных дуэлей}
{104000}{}{Македонский меч}
{104001}{}{Какой блять македонский меч, вы о чём?}


{110000}{}{!Used in engine! default armor}
{110100}{}{Смокинг}
{110101}{}{Вечерний чёрный пиджак с открытой грудью и длинными, обшитыми шёлком лацканами. К смокингу полагаются тугая крахмальная манишка, стоячий воротничок с загнутыми углами, чёрный галстук-бабочка, туфли из тонкой кожи, но не лакированные, чёрный жилет или пояс-кушак камербанд (cummerbund).}
{110200}{}{Варварская броня}
{110201}{}{}
{110900}{}{Потрепанный Деревянный Щит}
{110901}{}{Потрепанный Деревянный Щит.}
{111000}{}{Деревянный Щит}
{111001}{}{Деревянный Щит.}
{111100}{}{Железный Щит }
{111101}{}{Железный Щит.}
{111200}{}{Стальной Щит }
{111201}{}{Стальной Щит.}
{111300}{}{Добротный Железный Щит }
{111301}{}{Добротный Железный Щит.}
{111400}{}{Щит Силы}
{111401}{}{Щит Силы.}
{111500}{}{Теневой Щит}
{111501}{}{Теневой Щит.}
{111600}{}{Щит Нарушитель Потока}
{111601}{}{Щит Нарушитель Потока.}
{111700}{}{Зачарованный Щит}
{111701}{}{Зачарованный Щит.}
{111800}{}{Магический Щит}
{111801}{}{Магический Щит.}
{111900}{}{Мистический Щит}
{111901}{}{Мистический Щит.}
{112000}{}{Тайный Щит}
{112100}{}{Кожаный Доспех}
{112101}{}{Кожаный Доспех.}
{112200}{}{Маленький Кожаный Доспех}
{112201}{}{Маленький Кожаный Доспех.}
{112300}{}{Большой Кожаный Доспех}
{112301}{}{Большой Кожаный Доспех.}
{112400}{}{Черная Кожаная Броня }
{112401}{}{Черная Кожаная Броня.}
{112500}{}{Серая Кожаная Броня }
{112501}{}{Серая Кожаная Броня.}
{112600}{}{Клепанная Броня }
{112601}{}{Клепанная Броня. }
{112700}{}{Маленькая Клепанная Броня}
{112701}{}{Маленькая Клепанная Броня.}
{112800}{}{Большая Клепанная Броня}
{112801}{}{Большая Клепанная Броня.}
{112900}{}{Кожа Дракона }
{112901}{}{Кожа Дракона.}
{113000}{}{Маленькая Кожа Дракона }
{113001}{}{Маленькая Кожа Дракона.}
{113100}{}{Большая Кожа Дракона}
{113101}{}{Большая Кожа Дракона.}
{113200}{}{Маленькая Кожанка из Драконей Кожи}
{113201}{}{Маленькая Кожанка из Драконей Кожи.}
{113300}{}{Маленькая Мистическая Кожаная Броня}
{113301}{}{Маленькая Мистическая Кожаная Броня.}
{113400}{}{Мистическая Кожаная Броня}
{113401}{}{Мистическая Кожаная Броня.}
{113500}{}{Большая Мистическая Кожаная Броня}
{113501}{}{Большая Мистическая Кожаная Броня.}
{113600}{}{Броня Пресмыкающегося}
{113601}{}{Броня Пресмыкающегося.}
{113700}{}{Магическая Кожаная Броня}
{113701}{}{Магическая Кожаная Броня.}
{113800}{}{Маленькая Магическая Кожаная Броня}
{113801}{}{Маленькая Магическая Кожаная Броня.}
{113900}{}{Большая Магическая Кожаная Броня}
{113901}{}{Большая Магическая Кожаная Броня.}
{114300}{}{Тайная Кожаная Броня}
{114301}{}{Тайная Кожаная Броня.}
{114400}{}{Маленькая Тайная Броня }
{114401}{}{Маленькая Тайная Броня.}
{114500}{}{Большая Тайная Кожаная Броня}
{114501}{}{Большая Тайная Кожаная Броня.}
{115200}{}{Золотое Кольцо}
{115500}{}{Зачарованное Кольцо}
{115600}{}{Тайное Кольцо}
{115700}{}{Изумрудное Кольцо}
{115800}{}{Рубиновое Кольцо}
{115900}{}{Сапфировое Кольцо}
{116000}{}{Бриллиантовое Кольцо}
{116100}{}{Деревянное Кольцо }
{116200}{}{Серебрянное Кольцо }
{116300}{}{Мифриловое Кольцо }
{116400}{}{Кольчужная броня}
{116401}{}{Кольчужная броня.}
{116500}{}{Маленькая Кольчужная Броня}
{116501}{}{Маленькая Кольчужная Броня.}
{116600}{}{Мифрильная Кольчуга }
{116601}{}{Мифрильная Кольчуга.}
{116700}{}{Маленькая Мифрильная Кольчуга }
{116701}{}{Маленькая Мифрильная Кольчуга.}
{116800}{}{Смазанная Кольчуга }
{116801}{}{Смазанная Кольчуга.}
{116900}{}{Маленькая Смазанная Кольчуга }
{116901}{}{Маленькая Смазанная Кольчуга.}
{117000}{}{Сверхлегкая Кольчуга}
{117001}{}{Сверхлегкая Кольчуга.}
{117100}{}{Маленькая Сверхлегкая Кольчуга}
{117101}{}{Маленькая Сверхлегкая Кольчуга.}
{117200}{}{Большая Сверхлегкая Кольчуга}
{117201}{}{Большая Сверхлегкая Кольчуга.}
{117300}{}{Кольчуга Дварфов }
{117301}{}{Кольчуга Дварфов.}
{117400}{}{Эльфийская Броня}
{117401}{}{Эльфийская Броня.}
{117500}{}{Кольчуга Гномов}
{117501}{}{Кольчуга Гномов.}
{117600}{}{Магическая Кольчуга }
{117601}{}{Магическая Кольчуга.}
{117700}{}{Маленькая Магическая Кольчуга }
{117701}{}{Маленькая Магическая Кольчуга.}
{129300}{}{Кожаные Перчатки }
{129500}{}{Хорошие Ботинки Путешественника }
{129600}{}{Элегантные Ботинки }
{132400}{}{Элегантный Цилиндр }
{132500}{}{Цилиндр }
{132600}{}{Амулет Молоха}
{132601}{}{Амулет Молоха.}
{132700}{}{Амулет Тестера}
{132701}{}{Ого, да Вы тестер!}
{132800}{}{Цилиндр }
{132801}{}{Цилиндр.}
{132900}{}{Элегантный Цилиндр }
{132901}{}{Элегантный Цилиндр. }
{133000}{}{Хорошие Ботинки Путешественника }
{133001}{}{Хорошие Ботинки Путешественника.}
{133100}{}{Элегантные Ботинки }
{133101}{}{Элегантные Ботинки.}
{133200}{}{Кожаные Перчатки }
{133201}{}{Кожаные Перчатки. }
{133300}{}{Амулет Бедокаан}
{133301}{}{Амулет Бедокаан.}
{133400}{}{Амлует Арахнида}
{133401}{}{Амлует Арахнида.}
{204900}{}{Отметка клетки выхода на карте}
{204901}{}{Отметка клетки выхода на карте}
{205100}{}{Бочка}
{205101}{}{Обычная бочка, нечего не нее смотреть}
{206700}{}{Секретная блокировочная клетка}
{206701}{}{Если вы это видите, вините в этом технического разработчика.}
{214100}{}{Источник света}
{234400}{}{Клетка автоневидимости}
{234401}{}{Если вы это видите, вините в этом технического разработчика.}
{236700}{}{Растения}
{236701}{}{Похоже на мутировавшую капусту. Судя по всему, она очень любит теплую погоду.}
{401200}{}{Блокировщик прокрутки}
{401600}{}{Сетка выхода}
{401700}{}{Сетка выхода}
{401800}{}{Сетка выхода}
{401900}{}{Сетка выхода}
{402000}{}{Сетка выхода}
{402100}{}{Сетка выхода}
{402200}{}{Сетка выхода}
{402300}{}{Сетка выхода}
{403100}{}{Сетка выхода}
{403200}{}{Сетка выхода}
{403300}{}{Сетка выхода}
{403400}{}{Сетка выхода}
{403500}{}{Сетка выхода}
{403600}{}{Сетка выхода}
{403700}{}{Сетка выхода}
{403800}{}{Сетка выхода}
{403900}{}{Сетка выхода}
{404000}{}{Сетка выхода}
{404100}{}{Сетка выхода}
{404200}{}{Сетка выхода}
{404300}{}{Сетка выхода}
{404400}{}{Сетка выхода}
{404500}{}{Сетка выхода}
{404600}{}{Сетка выхода}
{459200}{}{Световая преграда}
{459201}{}{Световая преграда.}
{562100}{}{Стена}
{562200}{}{Стена}

{680000}{}{WestEast стена}
{680001}{}{Блокиратор стены}
{680100}{}{NorthSouth стена}
{680101}{}{Блокиратор стены}
{680200}{}{West стена}
{680201}{}{Блокиратор стены}
{680300}{}{North стена}
{680301}{}{Блокиратор стены}
{680400}{}{East стена}
{680401}{}{Блокиратор стены}
{680500}{}{South стена}
{680501}{}{Блокиратор стены}
{800100}{}{Стиратель клеток}
{2200000}{}{Средство от Легких Ран}
{2200001}{}{Лечит до 20 HP.}
{2200100}{}{Великое Исцеление}
{2200101}{}{Лечит до 80 HP.}
{2200200}{}{Снять легкую усталость}
{2200201}{}{Восстанавливает до 30 пунктов Усталости.}
{2200300}{}{Слезы Морганы}
{2200301}{}{Лечит до 120 пунктов Отравления, HP и Усталости.}
{2200400}{}{Снять сильную усталость}
{2200401}{}{Восстанавливает до 70 пунктов Усталости.}
{2200500}{}{Лекарство от Яда}
{2200501}{}{Лечит до 120 пунктов отравления.}
{2200600}{}{Замедлитель усталости}
{2200601}{}{Уменьшает усталость.}
{2200700}{}{Эссенция Интеллекта}
{2200701}{}{Поднмает интеллект.}
{2200800}{}{Зелье Ускорения}
{2200801}{}{Поднимает Скорость.}
{2200900}{}{Жидкость для Утолщения Кожи}
{2200901}{}{Поднимает сопротивляемость повреждениям.}
{2201000}{}{Яд Калиспи}
{2201001}{}{Поднимает сопротивляемость ядам.}
{2201100}{}{Хлеб}
{2201200}{}{Вода}
{2201300}{}{Целебная Мазь}
{2201301}{}{Лечит легкие раны}
{2201400}{}{Восстановитель выносливости}
{2201401}{}{Восстанавливает выносливость.}
{2201500}{}{Чудесное Средство}
{2201600}{}{Лекарство от Всего}
{2201601}{}{Лечит до 60 HP и Усталости.}
{2202100}{}{От яда}
{2202200}{}{Раствор Электролита}
{2202300}{}{Живая Вода Вархама}
{2202400}{}{Очиститель Монро}
{2202500}{}{Зелье Красноречия}
{2202600}{}{Элексир Телесной Доблести}
{2202700}{}{Пары Камфары}
{2202800}{}{Известные Кровяные Пилюли}
{2202900}{}{Нашатырный Спирт}
{2203000}{}{Сильный Яд}
{2203100}{}{Ограничитель выносливости}
{2203200}{}{Ускоренное Исцеление}
{2203300}{}{Ведьмовская Погибель}
{2203500}{}{Жир Большой Главной Змеи}
{2203600}{}{Яд}
{2203700}{}{Чудесное Снадобье}
{2203800}{}{Едкая Кислота}
{2203900}{}{Чувственный Соблазн}
{2204000}{}{Чувственный Запах}
{2204100}{}{Пивные Дрожжи}
{2204200}{}{Карболовая Кислота Пита}
{2204201}{}{Вы можете говорить с крысами...}
{2204300}{}{Галлюциноген}
{2204500}{}{Таблетки  Храбрости}
{2204600}{}{Вино}
{2204700}{}{Бинты}
{2204800}{}{Зелье Крысиный Язык}
{2204801}{}{Вы можете говорить с крысами...}
{2204900}{}{Вытяжка Камфоры}
{2205000}{}{Сахар}
{2205100}{}{Реаниматор}
{2205200}{}{Сладкие Печеньки}
{2205300}{}{Невероятный Препарат Руннера}
{2205301}{}{Увеличивает Интеллект до невероятных высот.}
{2205400}{}{Картошка}
{2205401}{}{Крошка Картошка}
{2205500}{}{Бутылочка Яда}
{2205600}{}{Пустая бутылочка из под Яда}
{2300000}{}{Кинжал}
{2300001}{}{Кинжал}
{2300100}{}{Меч}
{2300101}{}{Меч}
{2300200}{}{Топор}
{2300201}{}{Топор}
{2300300}{}{Булава}
{2300301}{}{Булава}
{2300400}{}{Револьвер}
{2300401}{}{Револьвер}
{2300500}{}{Широкий Меч}
{2300501}{}{Широкий Меч}
{2300600}{}{Лук}
{2300601}{}{Лук}
{2300700}{}{Дробовик}
{2300701}{}{Дробовик}
{2300800}{}{Посох}
{2300801}{}{Посох}
{2300900}{}{Отравленный Меч}
{2300901}{}{Отравленный Меч}
{2301000}{}{Слоновья Пушка}
{2301001}{}{Слоновья Пушка}
{2301100}{}{Жезл Тесла}
{2301101}{}{Жезл Тесла}
{2301200}{}{Огнемет}
{2301201}{}{Огнемет}
{2301300}{}{Околдованный Меч}
{2301301}{}{Околдованный Меч}
{2301400}{}{Клинок Прикосновения Вампира}
{2301401}{}{Клинок Прикосновения Вампира}
{2301500}{}{Хороший Револьвер}
{2301501}{}{Хороший Револьвер}
{2301600}{}{Магазинная Винтовка}
{2301601}{}{Магазинная Винтовка}
{2301700}{}{Охотничье Ружье}
{2301701}{}{Охотничье Ружье}
{2301800}{}{Ж. Д. Штырь}
{2301801}{}{Ж. Д. Штырь}
{2301900}{}{Сбалансированный Меч}
{2301901}{}{Сбалансированный Меч}
{2302000}{}{Пушка Бронвика}
{2302001}{}{Пушка Бронвика}
{2302100}{}{Ржавый Кинжал}
{2302101}{}{Ржавый Кинжал}
{2302200}{}{Хороший Стальной Кинжал}
{2302201}{}{Хороший Стальной Кинжал}
{2302300}{}{Метательный Кинжал}
{2302301}{}{Метательный Кинжал}
{2302400}{}{Механический Кинжал}
{2302401}{}{Механический Кинжал}
{2302500}{}{Кинжал Мага}
{2302501}{}{Кинжал Мага}
{2302600}{}{Кинжал Скорости}
{2302601}{}{Кинжал Скорости}
{2302700}{}{Ржавый Меч}
{2302701}{}{Ржавый Меч}
{2302800}{}{Добротный Меч}
{2302801}{}{Добротный Меч}
{2302900}{}{Элитный Меч Каладона}
{2302901}{}{Элитный Меч Каладона}
{2303000}{}{Рапира}
{2303001}{}{Рапира}
{2303100}{}{Короткий Меч}
{2303101}{}{Короткий Меч}
{2303200}{}{Кривая Сабля}
{2303201}{}{Кривая Сабля}
{2303300}{}{Катана}
{2303301}{}{Катана}
{2303400}{}{Широкий Кривой Меч}
{2303401}{}{Широкий Кривой Меч}
{2303500}{}{Меч Защиты}
{2303501}{}{Меч Защиты КБ+15}
{2303600}{}{Клинок Тихих Вод}
{2303601}{}{Клинок Тихих Вод, Урон +4, Призвать Зверя}
{2303700}{}{Ржавый Топор}
{2303701}{}{Ржавый Топор}
{2303800}{}{Добротный Топор}
{2303801}{}{Добротный Топор}
{2303900}{}{Топор Мощи}
{2303901}{}{Топор Мощи}
{2315000}{}{Жало}
{2315001}{}{Жало}
{2399600}{}{Стрела}
{2399601}{}{Стрела}
{2399700}{}{Пуля}
{2399701}{}{Пуля}
{2399800}{}{Батарея}
{2399801}{}{Батарея}
{2399900}{}{Топливо}
{2399901}{}{Топливо}
{2500000}{}{Свирель}
{2500001}{}{Мелодия свирели пьянила славную эльфийку и хоббит хитрый деяние свое свершил.}
{2500100}{}{Кольцо Всевластья}
{2500101}{}{Сила Великая в этом Кольце.}
{2500200}{}{Руда}
{2500300}{}{Сталь}
{2500400}{}{Валун}
{2500401}{}{Огромный валунище.}
{2501700}{}{Корень Гинка}
{2501800}{}{Стебель Кадуры}
{2501900}{}{Листья Коки}
{2502000}{}{Листья Табака}
{2503400}{}{Цветы Мака}
{2504400}{}{Грибы}
{2504500}{}{Ящик Виски}
{2504501}{}{Ящик Виски. }
{2504600}{}{Банковский Ящик}
{2504601}{}{Банковский Ящик.}
{2504700}{}{Голова Арахнида}
{2504701}{}{Голова Арахнида.}
