#
# Created 21.04.08, Cvet
#
# В данном файле сценаристы могут создавать свои строки.
#


{10}{}{Test0}
{11}{}{Test1}
{12}{}{Test2}
{13}{}{Test3}

{100}{}{Иди сюда, пьянь беспробудная!}
{101}{}{Ну что ты опять начинаешь...}
{102}{}{Я начинаю? Это ты не заканчиваешь. Пить. А у нас игра!}
{103}{}{Да мне все равно в каком состоянии, я и так карты насквозь вижу...}
{104}{}{Иди проспись, бестолочь! Если нас раскусят - я тебя собственными руками придушу!}

